### ISSUE TITLE
Object mapping exported as array in Return Mapper

### ISSUE THREAD

**Issue by ecarlier-tibco** [TIBCOSoftware/flogo#110]
Whenever I use the return mapper, map using Object Mapper, and export app as json, the return mapper config is wrong in the exported json (using type "array" instead of "object") --> I have to update every time type manually
If i leave "array" the mapping does not function as expected

attached return mapping config in web UI and the exported config
<img width="1044" alt="capture d ecran 2017-12-12 a 14 35 13" src="https://user-images.githubusercontent.com/19713379/33887581-785ec988-df4a-11e7-8a9b-678838e9988c.png">
`              
{
                "id": "actreturn_3",
                "name": "Return",
                "description": "Simple Return Activity",
                "type": 1,
                "activityType": "flogo-return",
                "activityRef": "github.com/TIBCOSoftware/flogo-contrib/activity/actreturn",
                "attributes": [
                  {
                    "name": "mappings",
                    "value": [
                      {
                        "mapTo": "Result",
                        "type": 4,
                        "value": {
                          "Code": 0,
                          "Received": "{{$flow.Name}}"
                        }
                      }
                    ],
                    "required": false,
                    "type": "array"
                  }
                ]
              }
`

**Comment by mellistibco** [comment]
That looks like the correct mapping. The object you specified is here and looks correct:

"value": {
            "Code": 0,
            "Received": "{{$flow.Name}}"
          }

**Comment by ecarlier-tibco** [comment]
What you highlighted is correct, yes. 
What is not is what comes after "type": "array"
I have to change it to "object"

Eric

**Comment by mellistibco** [comment]
Type array indicates that the return activities "mappings" field is an array. This is because you could have more than one mapping in the return activity, it does not indicate that your mapped object is an array.

**Comment by mellistibco** [comment]
The activity to handle the mappings/return vals: https://github.com/TIBCOSoftware/flogo-contrib/blob/master/activity/actreturn/activity.json

**Comment by ecarlier-tibco** [comment]
Oops. Ok. You're right.
Was misleaded as I had an issue last time. Did try several fixes, and thought this was the one causing problems. 
But no issue so closing
