### ISSUE TITLE
Flogo Web: How can you properly update an activity that has been already imported in flogo web ?

### ISSUE THREAD

**Issue by ecarlier-tibco** [TIBCOSoftware/flogo#112]
Don't know if it is documentation improvement or a feature request.
I did not find a way to force flogo web to refresh an already imported flogo activity, re-fetching from github ?

**Comment by ecarlier-tibco** [comment]
Thinking about it. Is it using the version attribute in the metadata to validate if it requires a re-fetch or not ?

**Comment by ayh20** [comment]
+1

**Comment by mellistibco** [comment]
Reinstalling the activity via WebUI will update it

**Comment by ecarlier-tibco** [comment]
Well. Maybe it is a specific scenario. But I had the case when:
- first install did not work because of some issues in my activity
- I did fixes in my activity and committed to github
- then on flogo web, re-did the install on the activity -> the install was directly failing not even trying to re-fetch.
- I then stopped and re-started my flogo-web to have a clean fresh setup, and then the install worked

I will try to reproduce

**Comment by mellistibco** [comment]
@ecarlier-tibco that is another issue. The Web UI hosts an instance of a Flogo app and installs the activities, triggers, etc into the app. When the activity, trigger, etc fails to install because it failed to build due to an error, etc the engine doesn't recover itself. We're working on a solution for this.

**Comment by ecarlier-tibco** [comment]
Ok thanks for the explanation. I will be closing this one. Do you have an id to track the resolution of the related issue ?

**Comment by mellistibco** [comment]
#114 is the issue we can use to track this problem.
