### ISSUE TITLE
Is it possible to create a new activity to retrieve some data then emit only average of each 5 data?

### ISSUE THREAD

**Issue by lwlwlwlw** [TIBCOSoftware/flogo#130]
Hi, I want to create my own activity to retrieve some data from sensors then emit only the average of each 5 data, i.e. accumulate first 4 incoming data and emit the average only when 5th data arrives. I could not find a way to do this, could you please help with an instruction or example? Thank you .

**Comment by mellistibco** [comment]
@lwlwlwlw Hi, take a look at the aggregate activity, this is the started of what you need. Right now it only supports averaging, however an acclamation option needs to be added.

https://github.com/TIBCOSoftware/flogo-contrib/tree/master/activity/aggregate

**Comment by lwlwlwlw** [comment]
Thank you for your help! 

PS, I have to change  activity.json to make it work.
from
 "allowed" : ["block_avg, moving_avg, timeblockavg"]
to
 "allowed" : ["block_avg", "moving_avg", "timeblockavg"]

**Comment by mellistibco** [comment]
Thanks @lwlwlwlw. I resolved it in PR TIBCOSoftware/flogo-contrib#184

**Comment by mellistibco** [comment]
Closing for now. Reopen or create a new issue if you have any problems with the aggregate activity. Feel free to submit a PR if you fix a bug, etc in the activity :)
