### ISSUE TITLE
Enhancement to support for session management

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/flogo#135]
Flogo needs support for session management. For activities that communicate using session based protocols (thinking JMS here) Flogo activities should be able to 'Register' a Session Handler within the Engine. When the activity Eval method is invoked it should pass within the context the Session Handler interface in order that a valid session can be retrieved (likely from a Pool).

Also Activities require the ability to support lifecycle events such as Start or Stop that are called on initial App instantiation and destruction in order to handle cleanup activities.

**Comment by mellistibco** [comment]
This has been implemented and is supported with connections.Refer to project-flogo/edge-contrib#14
