### ISSUE TITLE
Missing Body content on Post when exporting app from UI

### ISSUE THREAD

**Issue by rothsteh** [TIBCOSoftware/flogo#136]
Hi there, I have an app that I created in the UI. When I use the build function within the UI and download it, it works fine. When I try to build the app from the cli it is unable to map the content to the flow parameter I have defined and get the following error:

AddAttr - name: {Error.type}, type: string, value:mapper

2018-01-20 20:10:18.603 DEBUG  [engine] - AddAttr - name: {Error.message}, type: string, value:failed to resolve flow attr: 'bodyofcall', not found in flow

2018-01-20 20:10:18.603 DEBUG  [engine] - Done Executing A.instance [48ecf6a223e73ae472e8ffceebe1d176] - Status: 700

2018-01-20 20:10:18.603 DEBUG  [engine] - worker-3: Completed Request
 app json below. 

{
  "name": "LogPostData",
  "type": "flogo:app",
  "version": "0.0.1",
  "description": "",
  "triggers": [
    {
      "name": "Receive HTTP Message",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/rest",
      "description": "Simple REST Trigger",
      "settings": {
        "port": "9886"
      },
      "id": "receive_http_message",
      "handlers": []
    },
    {
      "name": "Receive HTTP Message (1)",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/rest",
      "description": "Simple REST Trigger",
      "settings": {
        "port": "9876"
      },
      "id": "receive_http_message_1",
      "handlers": [
        {
          "actionMappings": {
            "input": [
              {
                "mapTo": "bodyofcall",
                "type": 1,
                "value": "content"
              }
            ],
            "output": []
          },
          "settings": {
            "method": "POST",
            "path": "/sendsyslog",
            "autoIdReply": null,
            "useReplyHandler": "true"
          },
          "actionId": "testpost"
        }
      ]
    }
  ],
  "actions": [
    {
      "data": {
        "flow": {
          "name": "testpost",
          "type": 1,
          "attributes": [],
          "rootTask": {
            "id": "root",
            "type": 1,
            "tasks": [
              {
                "id": "log_2",
                "name": "Log Message",
                "description": "Simple Log Activity",
                "type": 1,
                "activityType": "github-com-tibco-software-flogo-contrib-activity-log",
                "activityRef": "github.com/TIBCOSoftware/flogo-contrib/activity/log",
                "attributes": [
                  {
                    "name": "message",
                    "value": "",
                    "required": false,
                    "type": "string"
                  },
                  {
                    "name": "flowInfo",
                    "value": "false",
                    "required": false,
                    "type": "boolean"
                  },
                  {
                    "name": "addToFlow",
                    "value": "false",
                    "required": false,
                    "type": "boolean"
                  }
                ],
                "inputMappings": [
                  {
                    "type": 1,
                    "value": "$flow.bodyofcall",
                    "mapTo": "message"
                  }
                ]
              },
              {
                "id": "SendSyslog_3",
                "name": "SendSyslog",
                "description": "Send a syslog message",
                "type": 1,
                "activityType": "github-com-lpautet-flogo-activities-send-syslog",
                "activityRef": "github.com/lpautet/flogo-activities/SendSyslog",
                "attributes": [
                  {
                    "name": "protocol",
                    "value": "udp",
                    "required": true,
                    "type": "string"
                  },
                  {
                    "name": "host",
                    "value": "lmi611test.howiedemo.com",
                    "required": true,
                    "type": "string"
                  },
                  {
                    "name": "port",
                    "value": "514",
                    "required": false,
                    "type": "integer"
                  },
                  {
                    "name": "facility",
                    "value": "16",
                    "required": true,
                    "type": "integer"
                  },
                  {
                    "name": "severity",
                    "value": "6",
                    "required": true,
                    "type": "integer"
                  },
                  {
                    "name": "hostname",
                    "value": "flogohost",
                    "required": false,
                    "type": "string"
                  },
                  {
                    "name": "appName",
                    "value": "flogoapp",
                    "required": false,
                    "type": "string"
                  },
                  {
                    "name": "msgId",
                    "value": null,
                    "required": false,
                    "type": "string"
                  },
                  {
                    "name": "flowInfo",
                    "value": "true",
                    "required": false,
                    "type": "boolean"
                  },
                  {
                    "name": "message",
                    "value": null,
                    "required": true,
                    "type": "string"
                  }
                ],
                "inputMappings": [
                  {
                    "type": 1,
                    "value": "$flow.bodyofcall",
                    "mapTo": "message"
                  }
                ]
              },
              {
                "id": "actreply_4",
                "name": "Reply To Trigger",
                "description": "Simple Reply Activity",
                "type": 1,
                "activityType": "github-com-tibco-software-flogo-contrib-activity-actreply",
                "activityRef": "github.com/TIBCOSoftware/flogo-contrib/activity/actreply",
                "attributes": [
                  {
                    "name": "mappings",
                    "value": [],
                    "required": true,
                    "type": "array"
                  }
                ]
              }
            ],
            "links": [
              {
                "id": 1,
                "from": "log_2",
                "to": "SendSyslog_3",
                "type": 0
              },
              {
                "id": 2,
                "from": "SendSyslog_3",
                "to": "actreply_4",
                "type": 0
              }
            ],
            "attributes": []
          }
        }
      },
      "id": "testpost",
      "metadata": {
        "input": [
          {
            "name": "bodyofcall",
            "type": "params"
          }
        ],
        "output": []
      },
      "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow"
    }
  ]
}

**Comment by mellistibco** [comment]
Can you try changing the type of the bodyofcall param to object?

"name": "bodyofcall",
"type": "object"
}

I tested and it seems to work

**Comment by rothsteh** [comment]
No luck still getting:


2018-01-21 21:41:10.675 DEBUG  [engine] - popped item off queue
2018-01-21 21:41:10.675 DEBUG  [engine] - Applying InputMapper
2018-01-21 21:41:10.675 DEBUG  [engine] - AddAttr - name: {Error.type}, type: st
ring, value:mapper

2018-01-21 21:41:10.676 DEBUG  [engine] - AddAttr - name: {Error.message}, type:
 string, value:failed to resolve flow attr: 'bodyofcall', not found in flow

2018-01-21 21:41:10.676 DEBUG  [engine] - Done Executing A.instance [b085dad42a7
3c3587cd585cfdf9a52e3] - Status: 700

2018-01-21 21:41:10.677 DEBUG  [engine] - worker-1: Completed Request

2018-01-21 21:41:10.677 DEBUG  [engine] - Run Action 'testpost' complete

**Comment by mellistibco** [comment]
What payload are you passing into the POST content?

**Comment by rothsteh** [comment]
A text value. “This is a test”. In the body of the post operation. 

It works when I build it using the web ui but not if I take the Json and export it. I need it on a platform I can’t build from the webui tho.

**Comment by mellistibco** [comment]
And you're just posting to http://localhost:9876//sendsyslog?

I suspect it is related to the lib and contrib versions that are pulled by the CLI. After you export the app json you're using flogo create -f to create the app structure?

**Comment by rothsteh** [comment]
Yep I’ve used postman t do it. I’ve tried both create -f and just a manual create followed by a build. Neither works.

**Comment by mellistibco** [comment]
Can you update the CLI?

go get -u github.com/TIBCOSoftware/flogo-cli/...

Validate that the binary was built just now:

ls -al $GOPATH/bin

If not, delete the bin and do the go get again.

**Comment by rothsteh** [comment]
Nope no luck :(

**Comment by mellistibco** [comment]
After updating the CLI did you try flogo create -f again? Also, what version of Go?

**Comment by rothsteh** [comment]
Yes tried that. Go version is go version go1.9.2 darwin/amd64

**Comment by rothsteh** [comment]
What is interesting is that the version on the UI is 1.7

**Comment by mellistibco** [comment]
Out of curiosity can you try the new dep branch for the CLI?

Install go dep (we'll be using this soon):
go get -u github.com/golang/dep/cmd/dep

cd $GOPATH/src/github.com/TIBCOSoftware
rm -rf flogo-cli
git clone flogo-cli
cd flogo-cli
git checkout dep
cd cmd/flogo
go install

Optionally, you can clone the repo some place else and go install cmd/flogo

Build your app structure again: flogo create -f ....

You should notice the new CLI using go dep is used. flogo build... and see if it works.

**Comment by rothsteh** [comment]
Got it working with the new CLI
