### ISSUE TITLE
Statement of Direction Link 404's

### ISSUE THREAD

**Issue by peter-mcrae** [TIBCOSoftware/flogo#14]
The link in Readme.md leads to a github 404 page.

**Comment by rkozhikk** [comment]
Thanks for raising, ack the issue and being addressed on priority.

**Comment by AnantaKaranam** [comment]
Is SOD finalize?

**Comment by Chandrian** [comment]
Flogo Statement of Direction link still lead to a 404 page....

**Comment by JGrotex** [comment]
Can we expected a fix on this one soon ?

**Comment by smanu** [comment]
N/A any more
