### ISSUE TITLE
flogo cli fails with FATAL error

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/flogo#159]
$ flogo create MyApp
Creating initial project structure, this might take a few seconds ... 
FATAL: command "create" failed: dep not installed

**Comment by mellistibco** [comment]
The cli has switched from gb to go dep:

https://tibcosoftware.github.io/flogo/getting-started/getting-started-cli/

**Comment by mmussett** [comment]
Broken on katacoda too…

**Comment by mellistibco** [comment]
ahh, nice catch! thanks @mmussett . @retgits can we fix on katakoda? :)

**Comment by retgits** [comment]
Katacoda has been fixed too 😄
