### ISSUE TITLE
Doc Enhancement request : create activity using a 3rd party go package

### ISSUE THREAD

**Issue by ecarlier-tibco** [TIBCOSoftware/flogo#16]
Hi,

I am a newbie at golang and I am struggling managing dependencies and imports correctly.
Using a 3rd party package shall be a very common practice when developing actvities. I followed the createactivity.md doc which is a good step-by-step manual. But, at the end, I fail make it work as my 3rd party package dependencies are clearly not well managed.
Can you please enhance the doc to clearly explain how to manage creating an activity using 3rd party go packages ?

Thanks
Eric

**Comment by torresashjian** [comment]
@ecarlier-tibco Can you please explain a little bit better what do you mean by 3rd party go packages? And add a step to step explanation on how to reproduce the issue if possible? 

Thank you very much!

**Comment by mellistibco** [comment]
Hi @ecarlier-tibco do you still feel this is needed? 3rd party packages don't really require any special management, you import them in your activity and thats pretty much it...

**Comment by ecarlier-tibco** [comment]
This can be closed. It was long time ago, and felt the need at that time because of an issue that was solved since
