### ISSUE TITLE
Flogo Web UI doesn't build for Windows

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#160]
The current Flogo Web UI doesn't build executables for Windows, whereas go is capable of doing so. Can we update the Web UI to allow builds of executables for Windows as well?

**Comment by fcastill** [comment]
About windows/amd64 and windows/386, do we need both options?

**Comment by mellistibco** [comment]
i'd just do x64, we should add both for linux, however...

**Comment by mellistibco** [comment]
resolved in 0.5.2
