### ISSUE TITLE
Flogo Web UI - Can't click on delete app after resizing window

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#161]
On my machine, I generally have multiple windows open side by side. When I resize the Flogo Web UI to 946 x 1080 (meaning half my screensize) I can still see the delete app button showing up when I hover over a card, but clicking it takes me to the app screen as opposed to prompting me to delete the app

![chrome_2018-02-20_10-45-55](https://user-images.githubusercontent.com/8568280/36442768-a8b1a8c2-162b-11e8-9437-83e4af270788.png)

**Comment by mellistibco** [comment]
@retgits is this still an issue? I just tested with the latest 0.5.6 release on Chrome and it works as expected.

**Comment by retgits** [comment]
Yes it is 😢 

<img width="851" alt="screen shot 2018-10-04 at 9 08 30 am" src="https://user-images.githubusercontent.com/8568280/46487577-3e1e9600-c7b5-11e8-87fc-aed381b00ce9.png">

When I resize my window to be a little smaller, so that the trash can appears at the place of the arrow, clicking the trashcan opens the app and doesn't delete it

**Comment by fcastill** [comment]
Fixed in v0.5.7
