### ISSUE TITLE
Flogo Web UI - Can't set environment variable for HTTP port

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#162]
I want to use environment variables in my Flogo app to control port numbers and things like that. In the `flogo.json` I can do that with the below snippet:
```
"settings": {
        "port": "$env.HTTPPORT"
      },
```
Unfortunately I cannot do that from the Web UI, nor does it show up when I import my flow into the Web UI. If I want to make use of this, I have to export my app and manually update the flogo.json (which is possible, but slightly less desirable)

**Comment by mellistibco** [comment]
@retgits thanks. We're looking to redesign the inputs a bit, rather than only allowing configuration via the right config window pane, we're thinking of consolidating configuration (like this) into the mapper, allowing you to map things like $env $properties etc.

**Comment by fcastill** [comment]
Starting from v0.5.5 we're supporting `$env[VAR_NAME]` and `$property[PROP_NAME]` for trigger/handler settings in the trigger configuration screen 😄
