### ISSUE TITLE
Slack/Gitter/Freenode channel?

### ISSUE THREAD

**Issue by peddamat** [TIBCOSoftware/flogo#171]
Hello,

I'm interested in contributing to the project and was wondering if the team had a public Slack, Gitter, or Freenode channel that I could jump on.

Best,

Sam

**Comment by mellistibco** [comment]
Hi @peddamat. We don't currently have a public channel, but do please feel free to ask questions via GitHub issues

**Comment by mellistibco** [comment]
Hi @peddamat a gitter channel has been created: https://gitter.im/project-flogo/Lobby
