### ISSUE TITLE
Can't build flogo app for Lambda

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#174]
Following the tutorial on the [Lambda](https://tibcosoftware.github.io/flogo/faas/how-to/) page, I get an error while running `flogo build -e -shim my_lambda_trigger`

The output of the error is
```
Shim: my_lambda_trigger
Id: my_lambda_trigger
Shim Metadata: plugin
Shim File: /mnt/c/tools/gosrc/src/flogoapps/lambda/src/lambda/vendor/github.com/TIBCOSoftware/flogo-contrib/trigger/lambda/shim/shim.go
Make File: /mnt/c/tools/gosrc/src/flogoapps/lambda/src/lambda/vendor/github.com/TIBCOSoftware/flogo-contrib/trigger/lambda/shim/Makefile
make: Entering directory '/mnt/c/tools/gosrc/src/flogoapps/lambda/src/lambda'
make: *** No targets specified and no makefile found.  Stop.
make: Leaving directory '/mnt/c/tools/gosrc/src/flogoapps/lambda/src/lambda'
FATAL: command "build" failed: exit status 2
```

**Comment by mellistibco** [comment]
thanks @retgits . It looks like the CLI isn't pulling down the shim dir for the trigger. looking into it

**Comment by mellistibco** [comment]
Quick workaround:

from the root of your flogo app:

vi src/lambda/Gopkg.toml

and comment out the prune section:

#[prune]
#  go-tests = true
#  unused-packages = true

**Comment by retgits** [comment]
Yeah, that workaround works :)

**Comment by mellistibco** [comment]
resolved, dont forget to update the cli:

go get -u github.com/TIBCOSoftware/flogo-cli/...

**Comment by vijaynalawade** [comment]
@mellistibco @retgits : How about below configuration?
```
# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

required = ["github.com/TIBCOSoftware/flogo-contrib/trigger/lambda/shim"]

[prune]
  unused-packages = true
  go-tests = true
```
Without prune settings, vendor directory will be populated with unused packages from all projects (repos).

**Comment by mellistibco** [comment]
makes sense @vijaynalawade. However we'll need to additional logic to the cli to identify if the trigger is a shim-style trigger, etc. I think we should test out pruning some more before enabling it again...
