### ISSUE TITLE
[WebUI] - Flow is rendered randomly with the activities defined in it

### ISSUE THREAD

**Issue by apandurangi** [TIBCOSoftware/flogo#175]
The flow is rendered differently every time I open the flow in Web UI. It happens in Chrome 64+ browser. 

First attempt: 
![image](https://user-images.githubusercontent.com/23206463/36965405-93accb60-207f-11e8-8e44-82d14623ca65.png)

Another attempt: 
![image](https://user-images.githubusercontent.com/23206463/36965464-b677d400-207f-11e8-888a-f4bad0309b81.png)

**Comment by achimera** [comment]
Thanks Anand for opening the issue!

**Comment by mellistibco** [comment]
A fix was added to Docker Hub for 0.5.1. Pull flogo/flogo-docker:latest from docker hub to grab the fix
