### ISSUE TITLE
flogo create fails when using ref anywhere

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#177]
After running
```
flogo create -f invoiceservice.json invoiceservice
```

The output is
```
Creating initial project structure, this might take a few seconds ... 
all dirs contained build errors
FATAL: command "create" failed: exit status 1
```

It seems that with the introduction of `dep` we traverse the JSON file and look for the `ref` element to populate the `imports.go`. If you're using `ref` anywhere else, as I've done in my mapping, Flogo will assume you need to import that URL too.

To fix this, you can follow this workaround:

* Open `imports.go`
* Remove the lines that do not start with  `github`
* Save the file
* Run `flogo ensure` from the root of your project

**Comment by vijaynalawade** [comment]
@retgits Please share your app.

**Comment by retgits** [comment]
Here it is @vijaynalawade https://github.com/retgits/flogo-components/blob/master/apps/invoiceservice/invoiceservice.json

**Comment by mellistibco** [comment]
@retgits this should be resolved in the latest master of flogo-cli
