### ISSUE TITLE
Params of type Object not manipulated correctly by inputMappings/Context

### ISSUE THREAD

**Issue by ecarlier-tibco** [TIBCOSoftware/flogo#18]
I attached a flow json to reproduce the problem.
Running this flow, you will that the rest activity is sending the string "null" as the body, whereas it should send "{ \"name\": \"my pet\"}", which is set by the inputMappings settings.

2 notes:
1) If you set 'content' as an attribute of the rest activity, the configured value is handled and passed correctly
2) I modified the rest activity to set type of 'content' to 'string', and the value set by inputMappings is passed and handled correctly

Thanks,
Eric
[testrest.json.zip](https://github.com/TIBCOSoftware/flogo/files/568994/testrest.json.zip)

**Comment by fm-tibco** [comment]
fixed in master and will be in 0.3.2 release
