### ISSUE TITLE
Debug - output versions

### ISSUE THREAD

**Issue by ayh20** [TIBCOSoftware/flogo#216]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
At present we have no idea what version is being used of flogo or the components or the flow 

**Expected behavior:**
When starting in debug, or with a -version flag on the exe .. or maybe in all modes we should print out a status line saying the component is using flow version 0.0.1 (from flog.json), trigger version from trigger.json and activities from activity.json etc

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**
Being able to better understand what version is being used on a deployed component.

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by retgits** [comment]
As a quick update, the `flogo-cli` now has a `version` command that will tell you which version of Flogo CLI you're running as well as which versions of flogo-contrib and flogo-lib are present in your project. This doesn't output the versions of the individual activities and triggers though.

**Comment by ayh20** [comment]
Leon, that's good to know but i'm thinking of the situation where we have a deployed executable .... how do you tell what it's built from ... which Flogo version, what flogo.json version, what version of activities etc ?

**Comment by retgits** [comment]
Hi @ayh20, the latest version of flogo-lib will now show versions. If the loglevel is set to debug it will print for activities:
```
Registering activity [ github.com/TIBCOSoftware/flogo-contrib/activity/log ] which has version [ 0.0.1 ]
```

for triggers it will print
```
Trigger [ my_rest_trigger ] has ref [ github.com/TIBCOSoftware/flogo-contrib/trigger/rest ]
```

for apps it will print
```
Starting app [ myNewApp ] with version [ 0.0.1 ]
```
