### ISSUE TITLE
Flogo UI launch

### ISSUE THREAD

**Issue by markrey** [TIBCOSoftware/flogo#22]
Hi,

Flogo project looks amazing.
I am interested in UI part of Flogo.

I will be creating and contributing integrations for

1. Scripting or function block. There are lots of native GO scripting interfaces available.
2. With our recently purchased IoT Cloud and Edge platform ( Litmus Loop and LoopEdge ).

Goal is create seamless REST API based ingestion / run script / send it to cloud.

Thanks,
Mark

**Comment by mellistibco** [comment]
Flogo Web UI is now available via a Docker Image on Docker Hub or at http://flogo.io
