### ISSUE TITLE
Support for ERROR branch

### ISSUE THREAD

**Issue by vijaynalawade** [TIBCOSoftware/flogo#221]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
Upon any error in main flow, execution flow goes to error handler and there is no way to go back to main flow.

**Expected behavior:**
In some cases, it is convenient to handle errors in the main flow itself and continue with the execution. e.g. Create file when file is not found.
In such cases, allowing ERROR branch from the activity would be really helpful to handle certain errors.

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
Closing, as this has been implemented. You can leverage error branching via the `branch` type on a link. For example:

```json
{
            "from": "xml2json_4",
            "to": "log_5",
            "type": "error"
          }
```
