### ISSUE TITLE
Issue running the go test command

### ISSUE THREAD

**Issue by kawatoto** [TIBCOSoftware/flogo#227]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[] feature request
[x] support request
[] general question
```

**Current behavior (how does the issue manifest):**
I'm building an activity, but when I run the go test command the below error appears:

adavilag-MBP13:sendMail adavilag$  go test
 github.com/TIBCOSoftware/flogo-contrib/action/flow/definition
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:82:13: cannot use value.Name (type func() string) as type string in map index
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:145:19: cannot use value.Name (type func() string) as type string in map index
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:174:53: cannot use attr.Type (type func() data.Type) as type data.Type in argument to data.CoerceToValue
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:179:50: unknown field 'Name' in struct literal of type data.Attribute (but does have data.name)
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:179:62: unknown field 'Type' in struct literal of type data.Attribute
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:179:80: unknown field 'Value' in struct literal of type data.Attribute (but does have data.value)
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:200:53: cannot use attr.Type (type func() data.Type) as type data.Type in argument to data.CoerceToValue
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:205:51: unknown field 'Name' in struct literal of type data.Attribute (but does have data.name)
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:205:63: unknown field 'Type' in struct literal of type data.Attribute
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:205:81: unknown field 'Value' in struct literal of type data.Attribute (but does have data.value)
../../src/github.com/TIBCOSoftware/flogo-contrib/action/flow/definition/definition_ser.go:205:81: too many errors
FAIL	_/Users/adavilag/go/bin/sendMail [build failed]

**Expected behavior:**

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
When was the last time you updated flogo-contrib and flogo-lib in your GOPATH?

**Comment by kawatoto** [comment]
When I updated flogo CLI tools (a few days ago), also I followed the instructions to do it in 

https://tibcosoftware.github.io/flogo/getting-started/getting-started-cli/

**Comment by mellistibco** [comment]
Can you share your activity?

**Comment by kawatoto** [comment]
Sure,

This is the activity.go

```
package sendMail

import (
	"log"
	"net/smtp"

	"github.com/TIBCOSoftware/flogo-lib/core/activity"
)

// MyActivity is a stub for your Activity implementation
type MyActivity struct {
	metadata *activity.Metadata
}

// NewActivity creates a new activity
func NewActivity(metadata *activity.Metadata) activity.Activity {
	return &MyActivity{metadata: metadata}
}

// Metadata implements activity.Activity.Metadata
func (a *MyActivity) Metadata() *activity.Metadata {
	return a.metadata
}

// Eval implements activity.Activity.Eval
func (a *MyActivity) Eval(context activity.Context) (done bool, err error) {

	// do eval
	emailFrom := context.GetInput("emailFrom").(string)
	password := context.GetInput("password").(string)
	emailServer := context.GetInput("emailServer").(string)
	emailTo := context.GetInput("emailTo").(string)
	body := context.GetInput("body").(string)

	// Set up authentication information.
	auth := smtp.PlainAuth(
		"",
		emailFrom,
		password,
		emailServer,
	)
	// Connect to the server, authenticate, set the sender and recipient,
	// and send the email all in one step.
	err = smtp.SendMail(
		emailServer+":465",
		auth,
		emailFrom,
		[]string{emailTo},
		[]byte(body),
	)
	if err != nil {
		log.Fatal(err)
	}

	context.SetOutput("result", "The email was sent to "+emailTo+" from "+emailFrom)

	return true, nil
}
```

And this is the activity_test.go
```
package sendMail

import (
	"io/ioutil"
	"testing"

	"github.com/TIBCOSoftware/flogo-contrib/action/flow/test"
	"github.com/TIBCOSoftware/flogo-lib/core/activity"
	"github.com/stretchr/testify/assert"
)

var activityMetadata *activity.Metadata

func getActivityMetadata() *activity.Metadata {

	if activityMetadata == nil {
		jsonMetadataBytes, err := ioutil.ReadFile("activity.json")
		if err != nil {
			panic("No Json Metadata found for activity.json path")
		}

		activityMetadata = activity.NewMetadata(string(jsonMetadataBytes))
	}

	return activityMetadata
}

func TestCreate(t *testing.T) {

	act := NewActivity(getActivityMetadata())

	if act == nil {
		t.Error("Activity Not Created")
		t.Fail()
		return
	}
}

func TestEval(t *testing.T) {

	defer func() {
		if r := recover(); r != nil {
			t.Failed()
			t.Errorf("panic during execution: %v", r)
		}
	}()

	act := NewActivity(getActivityMetadata())
	tc := test.NewTestActivityContext(getActivityMetadata())

	//setup attrs
	tc.SetInput("emailFrom", "youremail@gmail.com")
	tc.SetInput("password", "yourpwd")
	tc.SetInput("emailServer", "smtp.gmail.com")
	tc.SetInput("emailTo", "anotheremail@tibco.com")
	tc.SetInput("body", "Hello! This is an email sent from Flogo")

	act.Eval(tc)

	//check result attr
	result := tc.GetOutput("result")
	assert.Equal(t, result, "The email was sent to anotheremail@tibco.com from youremail@gmail.com")
}

```

**Comment by mellistibco** [comment]
@kawatoto I just tried and do not receive the errors that you're getting. I suspect you're referencing an older pull of flogo-contrib and flogo-lib. Try removing flogo-lib and flogo-contrib from your GOPATH and pulling again via go get or git clone...

**Comment by kawatoto** [comment]
Hi @mellistibco 
I tried to do that you recommended and try a fresh installation but now I'm getting the below message:

```
$ go get -u github.com/TIBCOSoftware/flogo-cli/...
package context: unrecognized import path "context" (import path does not begin with hostname)
```

**Comment by retgits** [comment]
Hi! Can you share the output of `go version` and `dep version`? The only time I've seen the exact issue you mentioned is when running an older version of Go. The context package was added in Go 1.7, so your version should be at least that (though for Flogo we recommend 1.9 or higher)

**Comment by kawatoto** [comment]
Hi @retgits 
```
$ go version
go version go1.10.1 darwin/amd64
```
```
$ dep version
dep:
 version     : v0.4.1
 build date  : 2018-01-27
 git hash    : 37d9ea0
 go version  : go1.9.3
 go compiler : gc
 platform    : darwin/amd64
```

**Comment by retgits** [comment]
Hmm okay, so the Go version can't be the problem there. I just tried a clean install of the Flogo cli on my Mac (after updating Go to 1.10.1), and I had no issues installing the flogo-cli. For me the outputs of the commands are:

```
$ go version
go version go1.10.1 darwin/amd64
```

```
$ dep version
dep:
 version     : v0.4.1
 build date  : 2018-01-27
 git hash    : 37d9ea0
 go version  : go1.9.3
 go compiler : gc
 platform    : darwin/amd64
```

And my `go env` looks like this
```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lstigter/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/lstigter/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2y/bx7fknx123z_f2k8gw15c3640000gn/T/go-build646893468=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

Can you check your `go env` and see if anything looks out of the ordinary? Also, have you tried getting other packages? I'm just wondering where to look next 😟

**Comment by kawatoto** [comment]
Hi @retgits 

My go env looks just like yours, but now the issue seems to be fixed, what I did was, I deleted my $GOHOME directory and installed everything again:

```
$go get -u github.com/TIBCOSoftware/flogo-cli/...
$go get -u github.com/golang/lint/golint

$go get github.com/TIBCOSoftware/flogo-lib/core/activity
$go get github.com/TIBCOSoftware/flogo-lib/logger
$go get github.com/TIBCOSoftware/flogo-contrib/action/flow/test
$go get github.com/stretchr/testify/assert
```

Now it is fixed, thanks for your help!

**Comment by retgits** [comment]
Good to hear and good luck! Please do let us know if the original issue running the `go test` command is solved as well.

**Comment by kawatoto** [comment]
Yes, the original issue was solved with the fresh installation!
