### ISSUE TITLE
Issue adding a custom activity

### ISSUE THREAD

**Issue by kawatoto** [TIBCOSoftware/flogo#229]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[] feature request
[X] support request
[] general question
```

**Current behavior (how does the issue manifest):**

Hi Team,

I'm trying to use the "Hello World" sample in the doc to add a new activity but it doesn't work, the activity name appears in the UI but I'm unable to add it into a flow.
Could you let me know if I'm missing a step?

Please find the github repo for your reference
[https://github.com/kawatoto/testFlogoActivity](url)

**Expected behavior:**

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by retgits** [comment]
Hi! To use the activity in the Flogo Web UI your `activity.json` needs a property called `ref`. In your case the attribute should have the value `github.com/kawatoto/testFlogoActivity`. Thanks for pointing out the issue in our documentation though! I'll make sure to update it.

**Comment by kawatoto** [comment]
Thanks Leon!
Now I can access to the activity.
