### ISSUE TITLE
Update all sample apps to reflect the new app model

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo#237]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[] feature request
[x] enhancement request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):** All the sample apps are still in the old app format and that should be updated to reflect the new format.

**Expected behavior:** The samples should reflect the new app model and should follow the structure where the README.md file explains what the sample is and does and an accompanying tutorial should be in the docs to explain in detail how to build the sample

## Status 
- [X] AWS IoT (PR: https://github.com/TIBCOSoftware/flogo/pull/348)
- [X] Hello World (PR: https://github.com/TIBCOSoftware/flogo/pull/348)
- [X] Tensorflow (PR: https://github.com/TIBCOSoftware/flogo/pull/425)
- [X] Get Book Sample (PR: https://github.com/TIBCOSoftware/flogo/pull/345)
- [X] Kubernetes (PR: https://github.com/TIBCOSoftware/flogo/pull/340)
- [X] PubNub (PR: https://github.com/TIBCOSoftware/flogo/pull/339)
- [X] Raspberry IoT (PR: https://github.com/TIBCOSoftware/flogo/pull/343)

**Comment by abramvandergeest** [comment]
I will try to do this for the ML stuff.  But I do not know what the "new app model" is.  if @mellistibco  @retgits  could tell me what the new app model is I would greatly appreciate it.

**Comment by fcastill** [comment]
I think this one: https://github.com/TIBCOSoftware/flogo/wiki/App-Model

Before this one there was a different model that didn't have the concept of "resources" and a few other variations in the structure.

**Comment by abramvandergeest** [comment]
Matt and I push the last inference/TF changes when we finished https://github.com/TIBCOSoftware/flogo/issues/413 as well.
