### ISSUE TITLE
CLI: Allow to specify a different flogo.json during flogo build

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo#238]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**

`flogo build` command by default uses the `flogo.json` file in the root of the project but specifying a different flogo.json to build would be helpful when I'm still making changes to my app and I don't want to overwrite my main flogo.json.

This would also be helpful for the Web UI so it can compile different apps without the need to create a second project.

**Expected behavior:**
Allow to specify the flogo.json file to build, maybe as an `-f` parameter to make it consistent with the `create` command.

Something like this:

```sh
flogo build -o -e -f /path/to/flogo.json
```
**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**

**Comment by mellistibco** [comment]
@skothari-tibco

**Comment by skothari-tibco** [comment]
I'll work on it.
