### ISSUE TITLE
Change the UI error for importing general category activities and triggers

### ISSUE THREAD

**Issue by gochani** [TIBCOSoftware/flogo#242]
When I export an app from Tibco Cloud Integration having general activity or trigger and import in 0.5.3 Flogo Web, error seen is -
"You need to install this ************* before you can use it in an app" Please see the attached screenshot.
However we do not have any way to install such things. We can only use activities and triggers which are a part of Flogo Web and opensource.

Expected Error should be: This *************** is not supported in Flogo Web.

![selection_042](https://user-images.githubusercontent.com/26763159/39118233-87fdcc6c-4706-11e8-9f5b-a6889eeb60ab.png)

**Comment by retgits** [comment]
Actually, the message is absolutely correct. You can install these activities and triggers provided you have access to the code to do so. In your case it seems you don’t have access to that code, but that doesn’t mean the error message is wrong.

**Comment by mellistibco** [comment]
The error message is valid, as @retgits said. Also refer to #218 for the suggested to change to imports.
