### ISSUE TITLE
OOB Memory and CPU profiling for Flogo application binaries

### ISSUE THREAD

**Issue by vijaynalawade** [TIBCOSoftware/flogo#243]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
Golang supports tooling for Memory and CPU profiling as described in https://blog.golang.org/profiling-go-programs.
Currently, there is no OOB way to enable CPU and Memory profiling for given app executable unless developers manually update main.go
**Expected behavior:**
**./binary** _-cpuprofile_ cupprof.prof _-memprofile_ memprof.prof
**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**
This will help debugging performance issues.
**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
0.5.3
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
resolved in TIBCOSoftware/flogo-cli#105
