### ISSUE TITLE
Flogo doc quick start out of date

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo#245]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
The quick start makes references to an older version of Flogo Web UI.

**Expected behavior:**
The quick start needs to be updated to reference the latest version of Web UI.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Look at the quick start: https://tibcosoftware.github.io/flogo/getting-started/quickstart/

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by vishwasrao** [comment]
Hi,
I would like to take this. 
Good to start with **good first issue** to contribute.
Thanks,
Vishwas

**Comment by mellistibco** [comment]
thanks @vishwasrao!

**Comment by vishwasrao** [comment]
@mellistibco 
I have updated issue templates for Bug Report, Feature request and support question.
It will look like below, Try by testing at my fork [FlogoRepo](https://github.com/vishwasrao/flogo)
If looks ok, I will create PR.
![image](https://user-images.githubusercontent.com/322956/39707890-447acffc-5233-11e8-819d-372acc6d7270.png)
