### ISSUE TITLE
Warn user when building/exporting apps with no trggers

### ISSUE THREAD

**Issue by rkozhikk** [TIBCOSoftware/flogo#250]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request
[] general question
```
**Current behavior (how does the issue manifest):**
Design an app that has one or more flows with no trigger. Build & run the app, it reports 
> [main-engine] - Failed to start engine due to error: unsupported resource type: flow

**Expected behavior:**
A simple warning should be provided to the user that s/he is exporting an app without any triggers. Applies to both Web UI  and CLI. 

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**
- Improve first time user experience ("so what's a flow, and what's a trigger?")
- Avoid user frustration 

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**
- OS: OSX 
- Browser: Chrome 65.0.3325.x
- Web UI: 0.5.3
- Docker: 0.17.0

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
- 0.5.3

**Additional information you deem important (e.g. issue happens only occasionally):**
Based on feedback from a new user.

**Comment by fcastill** [comment]
Included in v0.5.7

![trigger-warning](https://user-images.githubusercontent.com/17577698/49480774-d993ad80-f7dc-11e8-9d24-00deb9f80a6f.gif)
