### ISSUE TITLE
[Flogo Web] After one install new activity failed all will fail

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#257]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):** If there are error when you're importing a new activity (or if you by mistake click anywhere on the page to dismiss the install modal dialog), all subsequent imports of new activities will fail. 

**Expected behavior:** Don't fail for new installs

**Minimal steps to reproduce the problem (not required if feature enhancement):**

* Open Flogo Web UI
* Install a new activity
* Click anywhere on the page to dismiss the modal
* Try installing the same (or a different activity)

**What is the motivation / use case for changing the behavior?** Every time this happens I need to create a new docker instance 

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):** Flogo Web v0.5.3

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.5.3

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
Also tracked in issue #114

**Comment by retgits** [comment]
Okay, in that case I'm closing this one as a duplicate and will add my comments to that one :)
