### ISSUE TITLE
Timer trigger's default values are not exported.

### ISSUE THREAD

**Issue by KanchanPaul** [TIBCOSoftware/flogo#262]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
Timer trigger default values (repeating, notImmediate, startDate ) are not exported. 
  
**Expected behavior:**
Either default values should not be shown or if the default values are shown then it should be exported too.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
1)create a flow. 
2) Add a timer trigger
3) see the configuration tab with default values.
4) Export the app. 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.5.3

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
The default values defined in the activity or trigger.json are not carried into your app json, at runtime, the flow action will apply default values based on the activity/trigger json if no app values are defined.

**Comment by mellistibco** [comment]
The default values are now exported by the webui as of 0.5.6
