### ISSUE TITLE
Flogo documentation issue in Tutorial for Flogo CLI

### ISSUE THREAD

**Issue by opendevpmm** [TIBCOSoftware/flogo#263]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
Step 4 of the tutorial on the Katacoda site says that 'myapp' will be created in $GOPATH/bin, but it is actually created in $GOPATH/src/tutorial/myapp/bin

**Expected behavior:**
Text in the tutorial should match the seen result.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Run the tutorial instructions for Flogo CLI

**What is the motivation / use case for changing the behavior?**
Developers wanting to learn flogo will get confused and waste time.

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**
Irrelevant - tutorial is run on the Katacoda site (not locally).
**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by retgits** [comment]
Solved with update of the Katacoda tutorial
