### ISSUE TITLE
Flogo documentation Web UI tutorial - some issues

### ISSUE THREAD

**Issue by opendevpmm** [TIBCOSoftware/flogo#264]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
1. Step 5: When you click on the trigger, and then on the ‘configure’ option, it opens a window that does not look like the description provided. To get the correct configuration pane, you need to click on the trigger button instead.
2. Step 5: autoIdReply and useReplyHandler mentioned in the documentation are missing in the configuration pane.
3. Step 8, One final mapping step: The option is not ‘map flow params’ as the documentation says, rather it is ‘configure’. Also '{} data' (documented) is actually '* data'. 

**Expected behavior:**
Documentation should be consistent with the tool behaviour.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Run the tutorial for Web UI by strictly following the lab instructions.

**What is the motivation / use case for changing the behavior?**
Prevent confusion for new users trying out the flogo website.

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**
Katacoda environment.

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by retgits** [comment]
Solved with update of the Katacoda tutorial
