### ISSUE TITLE
Flogo web UI tutorial: suggested improvements to tutorial instructions

### ISSUE THREAD

**Issue by opendevpmm** [TIBCOSoftware/flogo#265]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
Some parts of the documentation instructions could be clarified more.

**Expected behavior:**
1. Step 5: method - use ‘GET’ instead of ‘get’. (this clarifies what is expected)
2. Step 6: Add ‘click Save’ at the end.
3. Step 7: Add ‘Choose the ‘Log message’ activity’. Also say ‘Leave the Output part blank’ to make it clear.
4. Step 8, Configure It. Add ‘click save’
5. Step 9: Mention: The running app can be stopped by clicking ctrl-C

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**
Making it easier for users to follow the lab instructions.

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**
Katacoda environment

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by retgits** [comment]
Solved with update of the Katacoda tutorial
