### ISSUE TITLE
Share connections between activities

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#270]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[] feature request
[X] support request
[] general question
```

**Current behavior (how does the issue manifest):** You cannot (easily) share connections between different activities. This means each activity will create and tear down the activity to an external system.

**Expected behavior:** Share connections between activities to share resources

**What is the motivation / use case for changing the behavior?** Having this available in an easier way for the developer would increase the speed of an app as not all activities have to instantiate their own connections.

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.5.3

**Comment by ayh20** [comment]
@retgits @mellistibco  This implies that there is a way of sharing connections today ... any info on how that can be done ? There's a few activities out there that would benefit greatly from this, however hard it is to do today ...

**Comment by mellistibco** [comment]
Thanks @retgits. Also tracked here #135.

@ayh20 technically activities instances are created only once, so you could share stuff between invocations if you wanted to... however, i'd suggest that we add some form of shared object access in the flow action and provide an api to store and fetch objects, etc.

**Comment by mellistibco** [comment]
Implemented. Refer to project-flogo/edge-contrib#14 for an example to use the new construct.
