### ISSUE TITLE
Please clarify the EULA

### ISSUE THREAD

**Issue by skurfuerst** [TIBCOSoftware/flogo#271]
First off -- the project looks EXTREMELY promising! Thank you so much for your work and for open sourcing it!

**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[x] general question
```

**Current behavior (how does the issue manifest):**

When checking out the website at http://www.flogo.io/, I need to accept the EULA before being able to "download" the docker image with the Flogo UI - and this PDF has 290 pages.

I understand that the Flogo "core" is licensed with very permissive open source licenses; and the web UI is not (yet?) open source.

I am wondering:

- can I use the Flogo web UI in commercial context?
- Do I need to take care of anything specifically to not violate the EULA?
- Do you plan to make the web UI commercial-only? (e.g. one has to pay after Beta)
- Is the web UI licensed for 90 days only?

**Expected behavior:**

It would be awesome to have some further description on flogo.io on the intention of the EULA :-)

**What is the motivation / use case for changing the behavior?**

I want to know whether it is safe to use Flogo in a more commercial-oriented setting; but to me it is only viable if the web UI can be used there as well :)

Again; thanks so much for this project, it looks really cool :-) Would be great to have the web UI parts clarified...

Thank you and all the best,
Sebastian

**Comment by mellistibco** [comment]
Hi @skurfuerst thanks for the question. You are correct, the webui is not yet open source, hence the license.

* Yes, you can use Flogo in a commercial setting.
* No, nothing special. The license applies only to the use of the web environment for building flows. not for the artifacts produced by Flogo.
* No, the web ui will not become commercial. It is free and the 90 day beta will auto renew.

I hope this helps. Let me know if you have any additional questions/concerns. Just to clarify, when you indicate a commercial-oriented setting. You're implying that you'll use Flogo to build commercial components? In other words, redistributing apps built with Flogo, not redistributing the webui, correct?

**Comment by skurfuerst** [comment]
Hey @mellistibco,

thanks for your super-fast response!

yeah that is totally correct. Not redistributing the Web UI, but redistributing Apps built with Flogo.

BTW - (a little off topic): I maybe wanted to extend the web UI a little such that it stores the json files in GitLab (via GitLab oAuth API) -- this way, by using GitLab CI, one could create a new flow in the UI; and get it auto-built and auto-deployed to a Kubernetes Cluster.
IMHO, when this is working, Flogo would be a great option for "serverless" use cases - as it also then provides some deployment story there instead of manually building it.

Would be curious to hear what you think about this :)

All the best,
Sebastian

**Comment by mellistibco** [comment]
@skurfuerst yup, awesome idea! In fact, we've been discussing the idea of integrating the webui with git for a few weeks now, so you could do exactly that workflow. Today, you'd need to create your app+flow(s) in the webui, export the app json, then add & commit to git, which could kick off the build and deploy workflow in your ci/cd pipeline.

I'll create a top level issue to track git integration with the webui.

**Comment by skurfuerst** [comment]
Sounds awesome, thanks :)

**Comment by skurfuerst** [comment]
II think we can close this issue as it is pretty much solved :+1:
