### ISSUE TITLE
Invoke Lambda MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#274]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):** If the payload of the Invoke Lambda activity is mapped as an object, all items that appear in the mapping array _after_ the payload are ignored.

**Expected behavior:** No mappings are ignored

**Minimal steps to reproduce the problem (not required if feature enhancement):**

* Create a new flow with the Invoke Lambda activity
* Set the payload to an object

Sample
```
{
    "type": "object",
    "value": {
        "Greeting": "Hello World"
    },
    "mapTo": "payload"
},
{
    "type": "literal",
    "value": "us-west-2",
    "mapTo": "region"
}
```

In this case the literal mapping for region is not passed into the engine. If you switch the order (have region appear before payload) it works perfectly fine

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):** Windows 10

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
```
flogo version
flogo cli version [v0.5.4]
Your project uses github.com/TIBCOSoftware/flogo-contrib version v0.5.4
Your project uses github.com/TIBCOSoftware/flogo-lib version v0.5.4
Your project uses github.com/retgits/flogo-components branch master and revision 6c85d7d9c68d9ad58550bf4778f7a3bb2eb70ac1
```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
@retgits can you test this with the master branch? This commit should have resolved the problem: https://github.com/TIBCOSoftware/flogo-lib/commit/78a727e6a8b3bccec34ce56338b1c30d2c653b6b

**Comment by retgits** [comment]
Yup, that does indeed seem to work! Closing this issue
