### ISSUE TITLE
How to use iterator values in object mapping?

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#275]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[] feature request
[X] support request
[] general question
```

**Current behavior (how does the issue manifest):** After creating an activity with an iterator, I can use the iterator values in `assign` type mappings but I can't seem to use them in `object` mappings

**Expected behavior:** Mapping should work

**Minimal steps to reproduce the problem (not required if feature enhancement):**

* Create a flow with an iterator activity, where one of the fields is of type object (I used `Invoke Lambda`)
* Create an object field using values from the iterator

Sample with `assign` that works
```
Mapping
{
 "type": "assign",
 "value": "$current.iteration.value.ID",
 "mapTo": "region"
}

Result
2018-05-18 22:24:36.821 DEBUG  [activity-tibco-lambda] - The region is set to 323861899
```

Sample with `object` that doesn't work
```
Mapping
{
    "type": "object",
    "value": {
        "EventVersion": "1.0",
        "EventSource": "aws:lambda",
        "Trello": {
            "Title": "{{$current.iteration.value.ID}}",
            "Description": "world"
        }
    },
    "mapTo": "payload"
}

Result
2018-05-18 22:32:30.077 DEBUG  [engine] - SetAttr: payload = map[EventVersion:1.0 EventSource:aws:lambda Trello:map[Title:<nil> Description:world]]
```

So in the latter case, the mapping isn't executed even though the object most certainly exists

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):** Windows 10

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
```
flogo version
flogo cli version [v0.5.4]
Your project uses github.com/TIBCOSoftware/flogo-contrib version v0.5.4
Your project uses github.com/TIBCOSoftware/flogo-lib version v0.5.4
Your project uses github.com/retgits/flogo-components branch master and revision 6c85d7d9c68d9ad58550bf4778f7a3bb2eb70ac1
```

**Comment by mellistibco** [comment]
@retgits I just tested and it seems to be working as expected in 0.5.6.
