### ISSUE TITLE
Cli trigger serializes default to a string and not a boolean

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#279]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):** When you add a CLI trigger to your flow and set the `default` parameter to `true`, the resulting flogo.json has `"default": "true"`

**Expected behavior:** The flogo.json should have `"default": true` so the flogo runtime recognizes it as a boolean

**Minimal steps to reproduce the problem (not required if feature enhancement):**

* Create a new app
* Add a CLI trigger
* Set default to true
* Export the app

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):** Windows 10, Web UI 0.5.4

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):**
```
λ flogo version
flogo cli version [v0.5.4]
Your project uses github.com/TIBCOSoftware/flogo-contrib version v0.5.4
Your project uses github.com/TIBCOSoftware/flogo-lib version v0.5.4
```

**Comment by mellistibco** [comment]
This has been resolved in 0.5.6
