### ISSUE TITLE
Expect proper error message to user: Flogo FAAS

### ISSUE THREAD

**Issue by debikadutt** [TIBCOSoftware/flogo#286]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
While working on deploying my app to AWS lambda I came across this issue: if my trigger ID in my json does not match the one which I supply to the CLI to create the zip file `flogo build -e -TRIGGER_ID` then the error shown to the user is a vague one and can be made more specific to let the user know about his mistake. The error currently shown is "`Shim Metadata lambda runtime.main_main·f: relocation target main.main not defined runtime.main_main·f: undefined: "main.main" FATAL: command "build" failed: exit status 2`"

**Expected behavior:**
A more informative error message

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Passing a different trigger_id to the above command other than the one in your json file.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**
Windows 10, Flogo Web UI 0.5.4

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
Flogo Web UI 0.5.4

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by retgits** [comment]
Thanks for suggesting this enhancement! We've updated the flogo-cli to give a proper message if the id of the trigger doesn't exist. In such a case you'll see a message like:
```
$ flogo build -e -shim my_lambda_trigger
Shim: my_lambda_trigger

Can't locate trigger with id [my_lambda_trigger] in flogo.json
Please check if you have specified the correct trigger id
```

You can get the latest version of the cli by running:
```
$ go get -u github.com/TIBCOSoftware/flogo-cli
```

**Comment by debikadutt** [comment]
Great! Thanks.
