### ISSUE TITLE
Modal buttons need 16px space

### ISSUE THREAD

**Issue by amandayam** [TIBCOSoftware/flogo#291]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
<img width="729" alt="screen shot 2018-06-05 at 11 26 29 am" src="https://user-images.githubusercontent.com/18149025/40995509-14fcc518-68b4-11e8-90cb-a51cb6ccead5.png">

**Expected behavior:**
16px margin between two buttons
<img width="338" alt="screen shot 2018-06-05 at 11 31 04 am" src="https://user-images.githubusercontent.com/18149025/40995462-f749b1c0-68b3-11e8-9314-24a99cc82973.png">

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**
Consistency

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by fcastill** [comment]
We fixed this and a few other visual consistency issues in v0.5.6
