### ISSUE TITLE
Google Chrome (browser) issue to view Triggers 

### ISSUE THREAD

**Issue by HiteshNembhwani** [TIBCOSoftware/flogo#297]
I don't get to see any triggers when I try to add a trigger and this problem is only with the Chrome browser, works well if I use Safari. 

Snapshot attached: 
<img width="1437" alt="screen shot 2018-06-15 at 5 38 43 pm" src="https://user-images.githubusercontent.com/17696107/41494053-23a6d470-70c3-11e8-9b29-03d3f78dee66.png">

I'm using Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by fcastill** [comment]
Just tried Flogo Web v0.5.4 in Chrome 67.0.3396.87 for mac and it is working for me 🤔

Can you please confirm you're running the latest version of the UI? You can see the version in the help menu in the top right corner:

<img width="435" alt="screen shot 2018-06-15 at 8 30 19 pm" src="https://user-images.githubusercontent.com/17577698/41495392-f7dd7138-70da-11e8-9be2-02e7f35b96e1.png">

Also

**Comment by mellistibco** [comment]
@HiteshNembhwani can you try clearing your browsers cache?

**Comment by HiteshNembhwani** [comment]
@fcastill says Flogo latest as the version, snapshot attached. 
@mellistibco tried cleared the cache and restarted the browser and that didn't help either. Tried Incognito as well but didm't work.. 
<img width="425" alt="screen shot 2018-06-17 at 1 01 48 pm" src="https://user-images.githubusercontent.com/17696107/41511595-df74af4e-722e-11e8-9430-7012f7cdad95.png">

**Comment by retgits** [comment]
Hmm that is interesting! Flogo should display a version number there... did you start the Flogo Web UI with ‘docker run -it -p 3303:3303 flogo/flogo-docker eula-accept’ or did you specify a certain build? 🤔

**Comment by HiteshNembhwani** [comment]
v0.5.4 had some issues so @mellistibco suggested to use flogo-web instead of flogo-docker for a demo.. irrespective of the version, I've been having this Chrome issue on earlier versions as well, happy to verify specific version as well, if needed.

**Comment by mellistibco** [comment]
Hey @HiteshNembhwani, just wanted to follow up on this. So it seems that the issue is related to hardware acceleration enabled in Chrome, correct? Did you get a chance to do any additional debugging?
