### ISSUE TITLE
Why should I invest in a technology when one of the most crucial part (the WEB UI) is not open source?

### ISSUE THREAD

**Issue by volkrass** [TIBCOSoftware/flogo#298]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[X] general question
```

**Current behavior (how does the issue manifest):**

**Expected behavior:**
Open Source the WEB UI to fulfill your marketing statements (fully open source & visual creation) 

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**
Otherwise the project is no really a open source project. 

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
Thanks @volkrass for the question. Flogo is much more than just a web-based dev environment. In fact, I would say Flogo is absolutely not a web-based dev platform, Flogo is truly an event driven framework. All of the framework code, such as the process engine, activity and trigger contributions, etc are all available as open source.

The web development environment is essentially just an app that is only used to visual model the application JSON. The application JSON is then compiled using the open source cli against the open source flogo-lib & flogo-contrib repos.

I hope that helps answer your question.

**Comment by hansamann** [comment]
I have the same issue - ideally the web ui would be open-sourced, too. Are there any plans to do this?

**Comment by mellistibco** [comment]
Hi @hansamann, Yes we do have plans to open source the UI.

**Comment by SvenDowideit** [comment]
@mellistibco are there any updates on this?

**Comment by mellistibco** [comment]
Hi @SvenDowideit thanks for checking in on the status. We're targeting first or 2nd week of March to open up the web ui repo. I'll keep you posted.

**Comment by SvenDowideit** [comment]
Ok, that is awesome news!

**Comment by vinodc** [comment]
Looking forward to checking it out as well. Is the plan still to open source the UI in the next week or two?

**Comment by mellistibco** [comment]
@vinodc it sure is, we're just working through a few last bugs, etc and we'll open source it along with the latest release of the core.

**Comment by mellistibco** [comment]
Hi all, the flogo web-ui has been open sources! Check out the source here: http://github.com/TIBCOSoftware/flogo-web
