### ISSUE TITLE
Remove six tile wide flow limitation

### ISSUE THREAD

**Issue by ayh20** [TIBCOSoftware/flogo#299]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[X] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
WebUI only allows you to create a flow that contains 6 tiles wide

**Expected behavior:**
Either unlimited or at least a high number of consecutive steps would be allowed.  Limitation doesn't exist in json config, nor does it exist in the commercial Enterprise version.

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**
Having 6 steps means that the UI is just a toy :-)

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.5.x

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by achimera** [comment]
Having this limit, would developers move away to use another environment to build visually microservice applications. It is fairly easy to hit that limit if you consider that with already two Log activities would leave space for another 4 slots to build logic. 

I disagree with the built-in limitation and agree with Andy.

**Comment by jvanderl** [comment]
+1
I've done some crazy stuff to get more complex logic fitted into flogo web, like a flow calling another flow using MQTT but you just hit that limit too soon.
I did hack the web UI to allow for a bigger number and that works. Just let me know if I should post that or not ;)

**Comment by mellistibco** [comment]
JFYI -- We can do a subflow invoke rather than calling another flow via MQTT 😄

**Comment by mellistibco** [comment]
the limit has been increased. if subflows do not help, please reopen this issue.
