### ISSUE TITLE
Rest Invoke activities saving skipSsl value as string instead of boolean while export

### ISSUE THREAD

**Issue by KanchanPaul** [TIBCOSoftware/flogo#300]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
Rest Invoke activities saving skipSsl value as a string instead of boolean while export. 
For example :   "skipSsl": **"true"**,
  
**Expected behavior:**
skipSsl value should be exported as boolean value 
For example :   "skipSsl": **true**,

**Minimal steps to reproduce the problem (not required if feature enhancement):**
1) Create a flow
2) Use Rest invoke activity in the flow. Configure all the values in configuration tab. 
3) Select true for skipssl radio button.
4) Export the file.
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
0.5.4, 0.5.5
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
Resolved in 0.5.6. The exported app maintains the type specified in the ui.
