### ISSUE TITLE
Support negative numbers in literal expressions

### ISSUE THREAD

**Issue by ecarlier-tibco** [TIBCOSoftware/flogo#301]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
the following expression for instance does not work:
"$.content.ParamNb3 != nil ? $.content.ParamNb3 : -1"
whereas this same one but with a positive works:
"$.content.ParamNb3 != nil ? $.content.ParamNb3 : 9999"

**Minimal steps to reproduce the problem (not required if feature enhancement):**
flogo.json attached
 
**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
0.5.4

[flogo.json.zip](https://github.com/TIBCOSoftware/flogo/files/2144399/flogo.json.zip)

**Comment by mellistibco** [comment]
Resolved with TIBCOSoftware/flogo-lib#219
