### ISSUE TITLE
Katacoda lab "Getting started with the flogo web UI" needs update

### ISSUE THREAD

**Issue by vrrobz** [TIBCOSoftware/flogo#312]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[] feature request
[X] support request
[] general question
```

**Current behavior (how does the issue manifest):**
The "Getting started with the flogo web UI" code lab on Katacoda (https://katacoda.com/retgits/scenarios/flogo-webui) contains a few errors that would make it difficult for someone new to the project to get around.

On Step 6: It says to "click on the large grey box called Flow params", but no such box exists on the current page. Clicking on "Input / Output" next to the trigger does cause a popover that says "Define params". Unclear how to add the params given current wording. 

On Step 8: It says, "You can paste in string.concat(\"Hello \", $flow.name) and click the big blue save button to complete this step". When one cuts and pastes this directly - with backslashes intact - the final product responds with the exact code, not with the interpreted value. The backslashes are not only unecessary, they actively break the expected output. 

Also Step 8: It says "Select the option for Trigger Reply on the left hand side..." No such option exists. Instead, there is a tab at the top that says "Map from Flow Output", which appears to be the correct one. 

**Expected behavior:**

As mentioned above, the documentation does match the UI. I expect it to match.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
See above.

**What is the motivation / use case for changing the behavior?**
This will stymie any new developers just trying to get familiar with the Web UI.

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

Mac OS X 10.13.5, Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
Whatever is in Katacoda

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by retgits** [comment]
Hi Rob, thanks for letting us know! I've updated the scenarios and as soon as the builds are picked up by Katacoda you should see the updates.
