### ISSUE TITLE
Go API doesn't respond with values

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#318]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):** I've built a few apps using the Go API as documented on https://github.com/TIBCOSoftware/flogo/wiki/Go-App-Api-Proposal (see source at https://github.com/retgits/flogo-components/tree/master/apps/invoiceservice-go and https://github.com/retgits/flogo-components/tree/master/apps/paymentservice-go). As I'm running my apps, the apps execute properly but never respond with a value (there seems to be no data returned to the trigger)

**Expected behavior:** The triggers should respond with the data

**Minimal steps to reproduce the problem (not required if feature enhancement):**

* Build one of the samples I've listed above
* Run the app
* No data is returned 😢 

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):** 0.5.5

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.5.5

**Comment by fm-tibco** [comment]
can you try this sample app:

```
package main

import (
	"context"

	"github.com/TIBCOSoftware/flogo-contrib/activity/log"
	"github.com/TIBCOSoftware/flogo-contrib/trigger/rest"
	"github.com/TIBCOSoftware/flogo-lib/core/data"
	"github.com/TIBCOSoftware/flogo-lib/engine"
	"github.com/TIBCOSoftware/flogo-lib/flogo"
	"github.com/TIBCOSoftware/flogo-lib/logger"

	_ "github.com/TIBCOSoftware/flogo-contrib/activity/log"
)

//go:generate go run $GOPATH/src/github.com/TIBCOSoftware/flogo-lib/flogo/gen $GOPATH

func main() {

	app := app1()

	e, err := flogo.NewEngine(app)

	if err != nil {
		logger.Error(err)
		return
	}

	engine.RunEngine(e)
}

func app1() *flogo.App {
	app := flogo.NewApp()

	trg := app.NewTrigger(&rest.RestTrigger{}, map[string]interface{}{"port": 8080})
	trg.NewFuncHandler(map[string]interface{}{"method": "GET", "path": "/blah"}, RunActivities)

	return app
}

func RunActivities(ctx context.Context, inputs map[string]*data.Attribute) (map[string]*data.Attribute, error) {

	in := map[string]interface{}{"message": "test"}
	_, err := flogo.EvalActivity(&log.LogActivity{}, in)

	if err != nil {
		return nil, err
	}

	ret := make(map[string]*data.Attribute)
	ret["code"], _ = data.NewAttribute("code", data.TypeInteger, 200)
	ret["data"], _ = data.NewAttribute("code", data.TypeAny, "return data")

	return ret, nil
}
```

**Comment by fm-tibco** [comment]
The issue I believe is the return.  You have to look at the metadata of the trigger to see what it expects as a reply.  In the REST case it will be code and data.  In your examples you might want to consider constructing an object/map an returning that as the data.

**Comment by fm-tibco** [comment]
We plan on working on the metadata issue.  You have to currently look at the json to see the metadata.  We need to look at options that will simplify this aspect of the API.  Same goes for the input/output of an Activity

**Comment by retgits** [comment]
This works! Thanks!!
