### ISSUE TITLE
Web UI is building apps against a different library version

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo#320]
> Note: Workaround explained below.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
When clicking "Build" option for an app the build process is using the "master" version of `flogo-lib` and not the version it was tagged for.

In console it can be observed `@master` tag is used:

```
info: run command: flogo create -flv github.com/TIBCOSoftware/flogo-contrib/activity/log@master,github.com/TIBCOSoftware/flogo-lib/app/resource@master -f /tmp/flogo-web/build/server/local/engines/exported-app-build.json -vendor local/engines/flogo-web/src/flogo-web/vendor app-build
```

**Expected behavior:**
App should use the flogo-lib version that corresponds to the docker image tag.

**Minimal steps to reproduce the problem (not required if feature enhancement):**

1. Start a flogo web instance
1. Open the default app
1. Click "Build" option and select a env/os target

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.5.4

**Additional information you deem important (e.g. issue happens only occasionally):**

Workaround: specify FLOGO_LIB_VERSION matching the version of the docker image when starting the container, for example:

```
docker run -it -p 3033:3303 -e "FLOGO_LIB_VERSION=v0.5.4" flogo/flogo-web:v0.5.4 eula-accept
```

**Comment by mellistibco** [comment]
Resolved in 0.5.5 of webui
