### ISSUE TITLE
Ability to do cleanup upon graceful app shutdown

### ISSUE THREAD

**Issue by vijaynalawade** [TIBCOSoftware/flogo#326]
**Current behavior:**
Currently, no mechanism for activity contributions to do cleanup of resources upon graceful shutdown of application.
**Expected behavior:**
There should be a mechanism to let contributions do cleanup upon graceful shutdown.
**What is the motivation / use case for changing the behavior?**
In certain cases, it is performant to maintain singleton connection across activity invocations. One should be able close this connection when app is shutdown.
**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by mellistibco** [comment]
Resolved in TIBCOSoftware/flogo-lib#207 and TIBCOSoftware/flogo-lib#209
