### ISSUE TITLE
Make configuring branches more user friendly (webui)

### ISSUE THREAD

**Issue by crmadrig** [TIBCOSoftware/flogo#328]
**Current behavior:**
At the moment when you add a branch to an activity you are just presented with a box to enter an if condition.
**Expected behavior:**
Make the branch configuration similar to the activity configuration. So provide "available data" suggestions that users can click which would fill in the if condition partially. Example: A branch coming out of a GPIO activity would have some "available data" suggestions such as $activity[gpio_2].result
**What is the motivation / use case for changing the behavior?**
Simplify how branches are configured within the webui. Reduces human error as people won't have to type as much.
**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by ayh20** [comment]
+1

**Comment by mellistibco** [comment]
Thanks @crmadrig. wip...
[ConfigBranch.pdf](https://github.com/TIBCOSoftware/flogo/files/2254247/ConfigBranch.pdf)

**Comment by retgits** [comment]
Hi @crmadrig, the latest version of Flogo Web (0.5.6) has a few improvements on this front. Configuration of a branch should now behave the same way as configuring an activity! Please let us know if that fixes your issues 😉
