### ISSUE TITLE
Documentation link points to GitHub repo

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#331]
**Current behavior:** In the Flogo Web UI, the documentation link for the triggers points to the GitHub repository of the trigger

**Expected behavior:** I'd expect that the Web UI would point to the documentation on our docs page

**What is the motivation / use case for changing the behavior?** The docs page has the relevant information

**Comment by mellistibco** [comment]
I would suggest that it continue to point to the trigger repo, as someone can have triggers installed that are not in flogo-contrib and thus not in the Flogo docs...

**Comment by retgits** [comment]
In that case, can't we have the links for triggers that come from flogo-contrib point to the docs and triggers that come from elsewhere point to a different page? The docs are the one single place where all information is captured together, so having links consistently point there would be very useful

**Comment by mellistibco** [comment]
Not really sure there is value in adding logic just for that... I would prefer consistency -- the contribution readme should be the place where someone would go for info on that contrib. 

We can perhaps also add a general docs link more prominently in the ui?

**Comment by retgits** [comment]
We should do that, no matter what :wink:  If I'm the only one that sees it as a problem, I guess we can keep it as is :innocent:
