### ISSUE TITLE
[Flogo Web] Back button not clickable on small screen

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#341]
**Current behavior (how does the issue manifest):** On a small screen the back button disappears behind the icon of the microservice making it impossible to click.

**Expected behavior:** Have the page scale properly or have scrollbars that make the buttons usable

**Minimal steps to reproduce the problem (not required if feature enhancement):** Create an app, open the app and resize the window

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):** Flogo Web 0.5.5

An image of the issue below:
![screenshot from 2018-08-15 08-05-04](https://user-images.githubusercontent.com/8568280/44155487-494122b6-a062-11e8-963f-01f485c25ebc.png)

**Comment by fcastill** [comment]
Fixed in v0.5.7
