### ISSUE TITLE
[Flogo Web] Settings in CLI trigger disappear after clicking save and closing window

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#342]
**Current behavior (how does the issue manifest):** In Flogo-Web, after creating a CLI trigger and configuring it, the value of the setting called `default` dissappears.

**Expected behavior:** Settings shouldn't dissappear

**Minimal steps to reproduce the problem (not required if feature enhancement):**

* Create an app
* Add a CLI trigger
* Open the CLI trigger
* Add `false` to the setting called `default`
* Click save and close the modal
* Open the CLI trigger -> default is now empty

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):** Flogo Web 0.5.5

**Comment by crmadrig** [comment]
Same thing happens with the MQTT Trigger. Cleansess is defined as an optional setting, but you can't save the trigger unless you enter something. 
So set Cleansess = false, save trigger configuration. Reopen trigger and you will see the Cleansess setting as empty.
