### ISSUE TITLE
[Flogo Web] Can't use functions in object mappings

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#344]
**Current behavior (how does the issue manifest):** I'm building a flow in which one of the fields in my response is the concatenation of two others. The mapping should look like
```
{
    "q": "{{string.concat("isbn:", $flow.isbn)}}"
}
```
In the Flogo Web UI I cannot create this expression as the validation of the field in the mapper throws an error (escaping the quotes surrounding isbn doesn't matter). When I export the app and build it through the commandline tools I can create the mapping
```
{
    "type": "object",
    "value": {
        "q": "{{string.concat(\"isbn:\", $flow.isbn)}}"
    },
    "mapTo": "queryParams"
}
```

**Expected behavior:** Mapping should work in both UI and CLI

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):** Flogo Web 0.5.5

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.5.5

**Comment by fcastill** [comment]
Functions and double quoted strings are supported in object values as long as the quotes are escaped:

![screen shot 2018-10-03 at 10 22 10 am](https://user-images.githubusercontent.com/17577698/46427429-4794f900-c6f6-11e8-9aff-5907cca9f275.png)
