### ISSUE TITLE
[Flogo Web] - Can't rename activities

### ISSUE THREAD

**Issue by crmadrig** [TIBCOSoftware/flogo#350]
**Current behavior (how does the issue manifest):**
Renaming activities don't save at the moment on Flogo Web v0.5.5-hf1
**Expected behavior:**
Ability to rename activities like in previous versions.
**Minimal steps to reproduce the problem (not required if feature enhancement):**
Create an activity. Rename. Create another activity, go back to the old activity, the rename didnt save.
**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**
Chrome, MacOS, Flogo web v0.5.5-hf1
**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by retgits** [comment]
Hi @crmadrig, with the latest version of the Flogo Web UI (0.5.6) this is fixed 😄 You can rename activities from the updated "configure" screen (just go to the configure screen and click on the name of the activity. A text box will appear where you can alter the name). Please do let us know if that fixes your issue!
