### ISSUE TITLE
Check if TF model exists before loading it/ better model loading error handling

### ISSUE THREAD

**Issue by abramvandergeest** [TIBCOSoftware/flogo#353]
**Current behavior:**
Loads the model fresh every time inference is needed even if model makes several inferences.

There is very little or no error handling of loading the model if no file exists, etc.

**Expected behavior:**

The model should only load a model if it is not already loaded.

Should have better error handling for model load.

**What is the motivation / use case for changing the behavior?**

A REST API that makes a prediction multiple times while the API service is up.  Especially if speed is needed for the inferences.

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by mellistibco** [comment]
Resolved in TIBCOSoftware/flogo-contrib#353
