### ISSUE TITLE
Error opening flogo app project: Invalid project, source directory doesn't exists

### ISSUE THREAD

**Issue by lwlwlwlw** [TIBCOSoftware/flogo#362]
**Current behavior (how does the issue manifest):**
I jsut want to check flogo version so I run "flogo version" on random folder(not a flog project folder) and I got the version info together with an error.
D:\tmp>flogo version
flogo cli version [v0.5.6]
Error opening flogo app project: Invalid project, source directory doesn't exists

**Expected behavior:**
The error is redundant.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
run "flogo version" inside a folder where no flogo project exists.

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
Windows 10/flogo 0.5.6

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by debovema** [comment]
Hi,

Fixed by TIBCOSoftware/flogo-cli#120

**Comment by retgits** [comment]
You can update the Flogo CLI by running `go get -u github.com/TIBCOSoftware/flogo-cli/...` and run the `flogo version` command to no longer see the error :) 

@debovema, thanks for the PR 😄
