### ISSUE TITLE
Flogo UI JSON App build problems, FATAL: command "create" failed: dep not installed   

### ISSUE THREAD

**Issue by ashdatla** [TIBCOSoftware/flogo#364]

**Comment by ashdatla** [comment]
I just created a new APP on the Flogo UI which has a simple Lambda trigger & a rest invoke. When i export the app and create a APP using the Json file it is failing with the following error 

Creating initial project structure, this might take a few seconds... 
FATAL: command "create" failed: dep not installed

**Comment by ashdatla** [comment]
{
  "name": "Lambda",
  "type": "flogo:app",
  "version": "0.0.1",
  "appModel": "1.0.0",
  "triggers": [
    {
      "id": "lambda_trigger_1",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/lambda",
      "name": "Lambda Trigger (1)",
      "description": "AWS Lambda Trigger used to start a flow as a function.",
      "settings": {},
      "handlers": [
        {
          "action": {
            "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow",
            "data": {
              "flowURI": "res://flow:lambda"
            },
            "mappings": {
              "input": [
                {
                  "mapTo": "input",
                  "type": "assign",
                  "value": "$.evt.txt"
                }
              ],
              "output": [
                {
                  "mapTo": "response",
                  "type": "assign",
                  "value": "$.status"
                }
              ]
            }
          }
        }
      ]
    }
  ],
  "resources": [
    {
      "id": "flow:lambda",
      "data": {
        "name": "Lambda",
        "metadata": {
          "input": [
            {
              "name": "input",
              "type": "string"
            }
          ],
          "output": [
            {
              "name": "response",
              "type": "string"
            }
          ]
        },
        "tasks": [
          {
            "id": "rest_2",
            "name": "Invoke REST Service",
            "description": "Simple REST Activity",
            "activity": {
              "ref": "github.com/TIBCOSoftware/flogo-contrib/activity/rest",
              "input": {
                "method": "GET",
                "uri": "http://13.229.231.252:8686/bot",
                "proxy": null,
                "pathParams": null,
                "queryParams": null,
                "header": null,
                "skipSsl": "false",
                "content": null
              }
            }
          },
          {
            "id": "actreply_3",
            "name": "Reply To Trigger",
            "description": "Simple Reply Activity",
            "activity": {
              "ref": "github.com/TIBCOSoftware/flogo-contrib/activity/actreply",
              "input": {
                "mappings": [
                  {
                    "mapTo": "response",
                    "type": "assign",
                    "value": "$activity[rest_2].result"
                  }
                ]
              }
            }
          }
        ],
        "links": [
          {
            "from": "rest_2",
            "to": "actreply_3"
          }
        ]
      }
    }
  ]
}

**Comment by retgits** [comment]
Hi! The CLI makes use of `dep` to get the dependencies and perform the build. You can install it using the instructions at https://github.com/golang/dep#setup

**Comment by mellistibco** [comment]
hi @ashdatla did you solve your problem?

**Comment by ashdatla** [comment]
Yes. I was able to seamlessly integrate my flogo lambda function which is interacting with a chatbot built on Lex and invoking functions deployed on BW & Data models. Thanks for the help. I will be publishing a demo soon on community and have that available.
