### ISSUE TITLE
change dependency name from Sirupsen to sirupsen

### ISSUE THREAD

**Issue by lwlwlwlw** [TIBCOSoftware/flogo#365]
**Current behavior (how does the issue manifest):**
Flogo uses github.com/Sirupsen/logrus, however it has been changed to github.com/sirupsen/logrus
with lowercase "sirupsen".

This (possibley) leads to error when run go get -u ...
github.com/sirupsen/logrus (download)
package github.com/sirupsen/logrus: case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"

**Expected behavior:**
Change Sirupsen to lowercase

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Run go get -u ...

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**
Flogo 0.5.6 on Windows 10

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
Flogo 0.5.6

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
Resolved
