### ISSUE TITLE
Contextual help for activities in UI

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/flogo#378]
**Current behavior:**
No help available in UI

**Expected behavior:**
Pull out menu should have 'Help' option that when clicked would open URL link to online documentation page for activity.

**What is the motivation / use case for changing the behavior?**
Improve UX for new users of Flogo. 

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by retgits** [comment]
Hi @mmussett, would your ideal solution be similar to what exists for triggers right now? In the trigger settings page, there is a `?` button that opens up the documentation for a specific trigger.

**Comment by mmussett** [comment]
My thoughts are adding '?' on to the tile like this....

![contextual help on flogo activity](https://user-images.githubusercontent.com/6975182/46433517-f7935200-c748-11e8-92e3-b3b6065580b0.png)

User clicks on '?' and Flogo UI launches a new browser page pointing to the homepage value stored in the activity.json.

**Comment by fcastill** [comment]
We've updated the tile design and decided to add the context help when editing an activity configuration.

In the activity edit screen:
![screen shot 2018-12-04 at 3 41 30 pm](https://user-images.githubusercontent.com/17577698/49480507-c6cca900-f7db-11e8-8680-f6839e251e4f.png)

And in the debugger panel:
![screen shot 2018-12-04 at 3 41 51 pm](https://user-images.githubusercontent.com/17577698/49480508-c6cca900-f7db-11e8-801d-820d5ba39b5a.png)
