### ISSUE TITLE
Property referenced in activity input is not resolved

### ISSUE THREAD

**Issue by vijaynalawade** [TIBCOSoftware/flogo#383]
**Current behavior (how does the issue manifest):**
For below activity input configuration, runtime throws error.
**App properties:**
`
 "properties":[
   {"name": "Message", "type": "string", "value": "Welcome to Flogo"},
   {"name": "Loglevel","type": "string", "value": "INFO"}
 ],
`

**Activity configuration in flow:**
`{
   "id": "flow:Test2",
   "data": {
    "name": "Test2",
    "tasks": [
     {
      "id": "LogMessage",
      "name": "LogMessage",
      "activity": {
       "ref": "github.com/vijaynalawade/flogo-contrib/activity/log",
       "input": {
        "Log Level": "$property[Loglevel]"
       },
       "output": {},
       "mappings": {
        "input": [
         {
          "mapTo": "message",
          "type": "assign",
          "value": "$property[Message]"
         }
        ]
       }
      }
     }`

**Runtime error:**
`Execution failed for Activity[LogMessage] in Flow[Test2] - Invalid Log level [$property[Loglevel]] configured in Activity [LogMessage] in Flow [Test2]. Valid values=[INFO, DEBUG, ERROR, WARN].`

**Expected behavior:**
'Log Level' must be set to INFO.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Define app property in exported flogo application and use that in activity input configuration.
**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
Resolved in TIBCOSoftware/flogo-contrib#297
