### ISSUE TITLE
Support for additional estimator model types

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo#393]
**Current behavior:**
Currently the Inference activity validates against dense features and only works for classifiers.

**Expected behavior:**
Expand the support for additional TensorFlow estimators.

**What is the motivation / use case for changing the behavior?**
Enable additional TensorFlow estimator models to be used within Flogo apps.

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by abramvandergeest** [comment]
To generalize for more estimators you have to rebuild the way the inference activity reads in inputs.  So this is effectively a duplicate of the" multiple feature inputs" issue.  see here: https://github.com/TIBCOSoftware/flogo/issues/402
