### ISSUE TITLE
Confusing documentation on create activity

### ISSUE THREAD

**Issue by mgyongyosi** [TIBCOSoftware/flogo#40]
Hey! 

Today I discovered this project and I find it interesting but the documentation seems a little bit confusing/outdated. I found two (+1 which is flogo_old) different docs on creating an activity:
1. https://github.com/TIBCOSoftware/flogo-cli/blob/master/docs/activity.md (`flogogen` works but where is the `-with-ui`, `-no-gb` parameter?)
2. https://github.com/TIBCOSoftware/flogo/blob/master/docs/createactivity.md

What is the current state of the tool? Are the `-with-ui`, `-no-gb` parameters deprecated?

Thanks

**Comment by mellistibco** [comment]
@mgyongyosi Sorry about the confusion around the documentation. We're working on fixing that. We've migrated activity scaffolding to flogogen. The -with-ui and -no-gb params are deprecated in flogogen.

As for as the state of the tool, development is active and we're working to add new features and functionality. We'll get the documentation cleaned up!

**Comment by mellistibco** [comment]
Updated create activity docs. Refer to https://tibcosoftware.github.io/flogo/docs/create-activity
