### ISSUE TITLE
Conditional router support in the handler

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo#406]
**Current behavior:**
Currently, the handler cannot introspect the payload and perform conditional routing to an action.

**Expected behavior:**
Support conditional routing in the handler.

**What is the motivation / use case for changing the behavior?**
Support payload routing to actions.

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by pointlander** [comment]
The trigger Handler implementation looks like this:

`type handlerImpl struct {
 runner action.Runner
 act    action.Action
 config *HandlerConfig
 actionInputMapper  mapper.Mapper
 actionOutputMapper mapper.Mapper
}`

but needs to look more like this:

`type act struct {
 expr expression.Expr
 act    action.Action
 actionInputMapper  mapper.Mapper
 actionOutputMapper mapper.Mapper
}

type handlerImpl struct {
 runner action.Runner
 config *HandlerConfig
 acts []act
}`

The first act with a true expr gets executed. An empty expression is considered to be true. It looks like the expression scripting engine doesn't support unmarshalled json (that has been unmarshalled into a map[string]interface{}), so this is something that potentially needs to be enhanced. Some consideration should be given to supporting other formats such as XML or Protobuf.
