### ISSUE TITLE
Include unit tests for Inference Activity

### ISSUE THREAD

**Issue by abramvandergeest** [TIBCOSoftware/flogo#407]
**Current behavior:**
No unit tests just has most recent test developer used (with path based off of their laptop)

**Expected behavior:**
Have basic unit tests with (very) small TF models included in the repo 

**What is the motivation / use case for changing the behavior?**
Much easy to test functionality of TF inferencing

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by abramvandergeest** [comment]
@mellistibco is ~80 kb all together too big for the models for the unit tests?

**Comment by mellistibco** [comment]
@abramvandergeest I think thats probably fine 👍

**Comment by abramvandergeest** [comment]
5 very simple Models included in Unit tests:
- DNN Classifier Estimator
- DNN Regressor Estimator
- Linear Regressor Estimator
- Simple CNN manual model
- pairwise matrix multiplication manual Model

https://github.com/TIBCOSoftware/flogo-contrib/pull/303#pullrequestreview-165312153
