### ISSUE TITLE
[Flogo Web UI] Activity list not updated after installing activity

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/flogo#409]
**Current behavior (how does the issue manifest):** After installing an activity using the "_install new activity_" button, the list isn't automatically refreshed, and the only way to see the new activity is by refreshing the browser window (or exiting the app)

**Expected behavior:** Installing a new activity should refresh the list automatically

**Minimal steps to reproduce the problem (not required if feature enhancement):**

* Create a new app (or open an existing one)
* Install a new activity from GitHub using the "_install new activity_" button

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):** Chrome browser (Version 69.0.3497.100 (Official Build) (64-bit)), Docker (18.06.1-ce), Flogo Web UI (0.5.6)

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.5.6

**Comment by apandurangi** [comment]
@retgits We noticed the same issue and [fixed](https://github.com/TIBCOSoftware/flogo-web/pull/872) it in v0.5.6. Could you please share the activity contribution url which you are trying to install?

**Comment by retgits** [comment]
It happens for any activity that I want to install, and I've tried about 20 of them (you can almost pick any of the ones I have in my GitHub repository: https://github.com/retgits/flogo-components)

**Comment by retgits** [comment]
Just to give an update for people seeing the same issue. Thanks to a debug session with @apandurangi and @fcastill, we found a workaround for this issue. In the dialog window where you paste the URL, simply remove the `https://` part (so make it a proper go import statement, like `github.com/retgits/flogo-components/activity/null`) and it will work.

**Comment by fcastill** [comment]
Fixed in v0.5.7
