### ISSUE TITLE
Banner print Application Name, Version and Details

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/flogo#411]
**Current behavior:**
None
**Expected behavior:**
Banner print Application Name and Details when application starts

**What is the motivation / use case for changing the behavior?**
Currently no information is printed. Would be great if we could have this banner printed to see what the app is.

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by retgits** [comment]
Hi Mark, with the debug log level (FLOGO_LOG_LEVEL=DEBUG) it will print the details of the app and the activities you're using. Is there anything you want to add there?

**Comment by mellistibco** [comment]
Resolved in TIBCOSoftware/flogo-lib#239
