### ISSUE TITLE
Failed to import flogo json with invoke rest service 

### ISSUE THREAD

**Issue by KanchanPaul** [TIBCOSoftware/flogo#412]
**Current behavior (how does the issue manifest):**
Failed to import flogo json with invoke rest service. 
It reports an error "Trigger is not installed".   

**Expected behavior:**
It should import flogo json without any error.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
1) Create a flow with "invoke rest service" activity
2) export the flogo json
3) import it back

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
Flogo version 0.5.6.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by fcastill** [comment]
Fixed in v0.5.7

Error was caused because of a validation error when importing an flow referencing tasks that didn't declare all the attributes defined in the activity schema.
