### ISSUE TITLE
Migrate away from `go dep` and move to go modules

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo#422]
**Current behavior:**
Many issues with `dep` & the go community is moving toward official support of package dep management via go modules.

**Expected behavior:**
Leverage go modules within the CLI. Also leverage submodules as appropriate for repos that containing more than one contrib.

**Comment by retgits** [comment]
We probably want to do that with the release of Go 1.12 as that would solidify the go modules even more (the Go team mentions the module workflow might still be updated)

**Comment by mellistibco** [comment]
Yup, supposedly future releases, like 1.12 will support modules defined in 1.11 🤞

**Comment by skothari-tibco** [comment]
I have been using the modules for over a month now and I find it pretty simple and clean. I think that's the same sentiment across the board. Also, Russ Cox has a video about modules and I'm pretty confident that they will moving forward with modules. So, What are the things you would like me to start with?
