### ISSUE TITLE
Support for otherwise branch 

### ISSUE THREAD

**Issue by vijaynalawade** [TIBCOSoftware/flogo#436]
**Current behavior:**
Today, there is no way for flow developer to add **otherwise** branch when one or more conditions do not match.
**Expected behavior:**
Flow developers should be able to configure otherwise branch and add logic there.
**What is the motivation / use case for changing the behavior?**
UX
**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by lixingwang** [comment]
@mellistibco  and @fm-tibco  Please give your ideas? thx

**Comment by fm-tibco** [comment]
we can add a link type, kind of how we have error link type.  We can then we only follow this link if it doesn't follow any other links, this should be pretty easy to do in the task behavior.

**Comment by lixingwang** [comment]
Thanks @fm-tibco And this is simple and I want to confirm you guys.  I will create PR soon
