### ISSUE TITLE
Activities having app properties configured should be in the format $property[xxx] not $property["xxx"]

### ISSUE THREAD

**Issue by gochani** [TIBCOSoftware/flogo#441]
Activities having app properties configured should be in the format $property[xxx] not $property["xxx"]

**Comment by lixingwang** [comment]
@gochani Could you please add more details here?  how you got the flogo.json and $property["xxx"] inside the json?

**Comment by lixingwang** [comment]
flogo-web doesn't support app property today. @gochani added app properties by hand and he uses `$property["xxxx"]` to resolve app property which is incorrect, it works fine after changing to `$property[xxxx]`, so close this ticket.
