### ISSUE TITLE
[WebUI] - Darwin build fails 

### ISSUE THREAD

**Issue by crmadrig** [TIBCOSoftware/flogo#451]
**Current behavior (how does the issue manifest):**
Create a project in the latest version of the WebUI (Flogo v0.5.7) and try to build the Darwin binary from the UI. Nothing happens after a certain amount of time. Check webui logs and you see an error was thrown. Building any other binaries (linux) works fine.

**Expected behavior:**
Darwin binary builds the same way that linux and windows do.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Build a project in the WebUI. You can test it out using the sample project provided at startup. 

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**
Chrome, MacOS, Docker version 18.09.0, WebUI version: Flogo v0.5.7

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**
Errors logs:
``` 
2019-01-09T21:54:05.462Z - error: # app-build/vendor/golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/fcntl_darwin.go:10:47: FcntlInt redeclared in this block
	previous declaration at vendor/golang.org/x/sys/unix/fcntl.go:16:47
vendor/golang.org/x/sys/unix/fcntl_darwin.go:15:51: FcntlFlock redeclared in this block
	previous declaration at vendor/golang.org/x/sys/unix/fcntl.go:26:51
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:576:99: sendfile redeclared in this block
	previous declaration at vendor/golang.org/x/sys/unix/syscall_darwin_amd64.go:51:80
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:17:51: getgroups redeclared in this block
	previous declaration at vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:17:51
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:28:44: setgroups redeclared in this block
	previous declaration at vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:28:44
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:38:82: wait4 redeclared in this block
	previous declaration at vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:38:82
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:49:73: accept redeclared in this block
	previous declaration at vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:49:73
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:60:62: bind redeclared in this block
	previous declaration at vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:60:62
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:70:65: connect redeclared in this block
	previous declaration at vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:70:65
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:80:58: socket redeclared in this block
	previous declaration at vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:80:58
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:80:58: too many errors
FATAL: command "build" failed: exit status 2 
```

**Comment by fcastill** [comment]
We're looking into this, it's seems to be a problem with `dep`, it's pulling code that targets go v1.11 but we have go v1.9 in the docker image.

**Comment by mellistibco** [comment]
We're still look into the issue, however, as a workaround, you can export the application .json file and use the flogo CLI (https://tibcosoftware.github.io/flogo/flogo-cli/flogo-cli/) to build the app for the desired target platform.

**Comment by fcastill** [comment]
This is fixed in v0.5.8 release which is now available in dockerhub

**Comment by rushabhnagda11** [comment]
@fcastill curious to know what you did to fix this. Going through something similar and you're the only github thread I've found that is very similar to my hunch.

**Comment by fcastill** [comment]
@rushabhnagda11 we upgraded the docker image to use go v1.11 😅 After that we dropped  `dep` support and started using Go modules instead and I haven't seen that issue again.

**Comment by rushabhnagda11** [comment]
Thanks! Info really helps.
