### ISSUE TITLE
Installation guideline without docker

### ISSUE THREAD

**Issue by ferllings** [TIBCOSoftware/flogo#452]
Hello,

Is there a guideline to install Flogo without using Docker?

Thanks

**Comment by retgits** [comment]
If you want to use the Flogo Web UI, unfortunately, there is no way of installing that without using Docker. We've chosen Docker to distribute that given the complexity of the UI and the dependencies it has.

If you want to just use the Flogo CLI and create your apps either using a JSON DSL or by using Go code, you can install the [Flogo CLI](https://tibcosoftware.github.io/flogo/getting-started/getting-started-cli/) and look at the [blue colored labs](https://tibcosoftware.github.io/flogo/labs/)

**Comment by JGrotex** [comment]
You can extract Flogo Web UI and run it natively on Linux. I have done this a while ago on a Raspberry Pi, as this is the only way to test custom Extensions against GPIO Interfaces, graphically in a complex Flow and debug them.
