### ISSUE TITLE
Function name and namespacing

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo#463]
In function descriptors, for example the [string functions descriptor](https://github.com/project-flogo/contrib/blob/5d885cb69df6791b2f87cdeddb5b16a9d1149532/function/string/descriptor.json) there's a concept of namespacing the function name but this is only by convention and also when specifying the function name we have to reiterate the namespace which becomes repetitive.

1. Should we move the namespace outside of the function name so we don't have to repeat it each time?
```diff
 {
   "name": "strings",
   "type": "flogo:function",
   "version": "0.0.1",
   "title": "String Functions",
   "description": "String Functions",
   "homepage": "https://github.com/project-flogo/contrib/tree/master/function/string",
+  "namespace": "string",
   "functions": [
     {
-      "name": "string.concat",
+      "name": "concat",
       ...
     },
     {
-      "name": "string.equals",
+      "name": "equals",
      ...
     },
     {
-      "name": "string.equalsIgnoreCase",
+      "name": "equalsIgnoreCase",
       ...
     },
     ...
   ]
 }
```
2. Should the namespace be enforced by the runtime?

**Comment by JGrotex** [comment]
have to say, I like this Idea a lot - also as this a lot simple in typing function's.

I was wondering why it can't find a know function, also it is a lot more error agnostic.

**Comment by fcastill** [comment]
Function descriptors are updated now to specify only the function name in the function entry, the namespace is given by the function package:  https://github.com/project-flogo/contrib/blob/master/function/string/descriptor.json
