### ISSUE TITLE
Not able to install the hello world activity via Web UI. Install failed message and no other details. FLOGO version being 0.5.8 and repo where activity is hosted is https://github.com/git-suraj/flogo/tree/master/HelloWorld (also tried with https://github.com/git-suraj/flogo/HelloWorld)

### ISSUE THREAD

**Issue by git-suraj** [TIBCOSoftware/flogo#472]
**What is your question?**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Comment by retgits** [comment]
Hi! 👋 can you try setting the `ref` in the `activity.json` to `github.com/git-suraj/flogo/HelloWorld`? The ref field should be the complete Go package name.

**Comment by git-suraj** [comment]
Hi, Am not able to install the hello world activity via Web UI. 
Getting a - Install failed message and no other details. FLOGO version being 0.5.8 and repo where activity is hosted is ˜ (also tried with https://github.com/git-suraj/flogo/HelloWorld).
I am following the tutorial - https://tibcosoftware.github.io/flogo/labs/building-activities/

Please help !

**Comment by git-suraj** [comment]
Hello !
Thanks for your response.
I did try as per your suggestion but no luck ! :(

**Comment by retgits** [comment]
Golang is case sensitive so it expects the package name to be the same case as the folder name. In your case the package name is `helloworld` but your folder name is `HelloWorld`. Both cases have to match.

The error you're getting in the logs of the Flogo Web UI should indicate the same issue: `imports.go:36:2: found packages helloworld (activity.go) and HelloWorld (activity_metadata.go)`

**Comment by git-suraj** [comment]
Thank you Leon !
Your suggestion worked perfectly !

**Comment by mellistibco** [comment]
Hi @git-suraj please reopen or create a new issue if you're having any other problems.
