### ISSUE TITLE
Error during Docker Run: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by giovannipersia** [TIBCOSoftware/flogo#481]
**Description**
I got an error trying to run docker image on a Raspberry Pi 3 with Rasbian (Linux raspberrypi 4.9.59-v7+) with command:
`sudo docker run -it -p 3303:3303 flogo/flogo-docker:latest eula-accept`

error returned is:
`standard_init_linux.go:207: exec user process caused "exec format error"`

**Steps to reproduce the issue:**

install docker: `curl -sSL https://get.docker.com | sh`
run latest flogo docker image: `sudo docker run -it -p 3303:3303 flogo/flogo-docker:latest eula-accept
`Describe the results you received:
error returned is:
`standard_init_linux.go:207: exec user process caused "exec format error"`

**Output of uname -a:**
`Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux`

**Comment by martirius** [comment]
I have the same error with a Raspberry Pi 3B+ but on a different line:
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by fcastill** [comment]
Can we see the rest of the logs?

I think this is an issue with the Flogo Web docker image not being compatible with the ARM architecture.

Suggestions and/or PRs about how to approach this issue are appreciated. This is our current Dockerfile for the Flogo Web docker image: https://github.com/project-flogo/flogo-web/blob/master/tools/docker/Dockerfile

**Comment by martirius** [comment]
@fcastill I'm sorry to say but this is the only message that i receive when i try to launch the container on a RPi 3B+.

**Comment by ayh20** [comment]
@martirius  Docker on a RPi requires a image built for the underlying hardware architecture (i.e. ARM).
If you want to build a docker container running a Flogo application then that's easy, but you need to generate the executable for ARM and build/package your container correctly for ARM.   The  Flogo webui is built for a x86 architecture, so will run on Mac/Windows/linux laptops/server/etc   but not on a RPi ..... Depending on what tools/products/libraries are used to build the WebUI there's no reason why it couldn't be done, but would require someone to spend a lot of effort to make it work.
For reference, is there a specific reason why you want to run the UI on a Pi ? We've seen people run Flogo apps on Pi but you're the first i've come across who wants to run the WebUI.

**Comment by martirius** [comment]
@ayh20 thanks for the clarification. 
The primary reason was that i misunderstood the real use of Flogo-WebUI, because i thought i could try the flow before "deploying" it.
However this is not possible, so for me is not an issue anymore because i launched  flogo container on my ubuntu machine and did the correct workflow (creating->building->deploy).

Thanks for the answers!
Cheers :)
