### ISSUE TITLE
Restarting Docker to resume test project.

### ISSUE THREAD

**Issue by JPAatWork** [TIBCOSoftware/flogo#50]
Can we update the documentation on what steps should be done to restart docker after a machine shutdown?  This way I can test with the same flogo image.

**Comment by retgits** [comment]
Hi John,

You can easily do that by issuing the docker start command for the image. You can find the container name by using the command `docker ps -a` and searching for the container with the image `flogo/flogo-docker`. Use the ID (or name) associated with the image to issue the docker start command e.g. `docker start b24e4b9f3fa5`

**Comment by mellistibco** [comment]
Resolved. Refer to documentation: https://tibcosoftware.github.io/flogo/docs/getting-started-webui
