### ISSUE TITLE
Configure Proxy in Flogo

### ISSUE THREAD

**Issue by akpuvvada** [TIBCOSoftware/flogo#514]
When I try to Build Flogo Apps from UI, I am getting failed message and when I check logs for the Flogo container, I am seeing error indicating that Flogo is not able to connect to git.
I have Proxy configured on Docker settings.
Any idea how to configure Proxy on Flogo?

**Comment by akpuvvada** [comment]
HI Matt, https://github.com/project-flogo/cli/issues/93 is related to CLI. This ticket is for UI. Not sure if both have same resolution.

**Comment by fcastill** [comment]
The UI uses the CLI internally so project-flogo/cli#93 might be related to this one. But I think we can keep this issue open until we get a resolution for the other one.

**Comment by akpuvvada** [comment]
Hi Castillo, The other one is resolved. Looks like the proxy URL was wrongly formatted. It is working now. How do you configure the Proxy in container/UI?
I already have Proxy configured for Docker.

**Comment by mellistibco** [comment]
@akpuvvada when running the docker image you set the environment variables?

**Comment by akpuvvada** [comment]
@fcastill , any idea if this can be fixed?

**Comment by mellistibco** [comment]
you should be able to run the docker image using the `-e` or `--env` switch to set the environment variable. It has been done in the past successfully. For example:

`docker run docker run -it -p 3303:3303 --env HTTP_PROXY="http://127.0.0.1:3001 flogo/flogo-docker eula-accept"

**Comment by akpuvvada** [comment]
Thanks, that worked. I am able to install plugins and build apps from UI directly from with-in our company Corp network.

**Comment by akpuvvada** [comment]
Thanks, that worked. I am able to install plugins and build apps from UI directly from with-in our company Corp network.
