### ISSUE TITLE
Sync switch for `flogo build`

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo#516]
**Current behavior (how does the issue manifest):**
When executing `flogo build` internally, the CLI runs a sync. This adds considerable time to the build. Should we consider an optional switch to execute sync rather than always executing it?

**Expected behavior:**
The build should be quicker.

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.9.4 (core) v0.9.1-rc.2 (cli)

**Comment by mellistibco** [comment]
@skothari-tibco did you resolve this already?

**Comment by skothari-tibco** [comment]
Yes. It's done.
