### ISSUE TITLE
Sample code on website is outdated

### ISSUE THREAD

**Issue by mingfang** [TIBCOSoftware/flogo#527]
The site http://www.flogo.io makes references to old and broken go packages such as
`github.com/TIBCOSoftware/flogo-lib`

vs the correct code in https://github.com/TIBCOSoftware/flogo/blob/master/README.md
`github.com/project-flogo/contrib`

I wasted hours following the wrong instructions.
Please update the main site immediately.

**Comment by mellistibco** [comment]
Hi @mingfang, really sorry about the confusion! We'll get that fixed today.

**Comment by mingfang** [comment]
@mellistibco still not fixed

**Comment by mellistibco** [comment]
Sorry @mingfang ! All fixed, in fact, the references have been updated in flogo.io, and the redirection to the readme is suggested for the go code sample.
