### ISSUE TITLE
[Question] UI Change

### ISSUE THREAD

**Issue by DarkBlaez** [TIBCOSoftware/flogo#535]
Maybe I am late to this party but when did the UI change? the current UI is horrible. The original UI was actually more aesthetically appealing. Now this looks like something IBM got ahold of and just clobbered the UI with a throw back to something uninteresting.

**Comment by mellistibco** [comment]
Thanks for the comment @DarkBlaez. Could you provide any specifics, what don't you like, what would you like to see changed, etc?

**Comment by mellistibco** [comment]
Closing this issue as no additional feedback was provided. Please reopen or create a new issue with specific items we can look at resolving.
