### ISSUE TITLE
Is Flows Web UI  proprietary? If not, how do I checkout and build?

### ISSUE THREAD

**Issue by anborg** [TIBCOSoftware/flogo#546]
Is Flows Web UI  proprietary? If not, how do I checkout and build?

I need to find a way to checkout and build without docker.

**Comment by mellistibco** [comment]
Hi @anborg no, its open source. The source is here: https://github.com/project-flogo/flogo-web

**Comment by anborg** [comment]
Ah , found the webui codebase after going through github issues. Will be great if this is included in the main page. 

https://github.com/project-flogo/flogo-web

Let me put a pull request, including the link in front page along with other
