### ISSUE TITLE
Flogo.json created by Flogo create command from flogo-cli is not being imported successfully in Flogo UI.

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/flogo#55]
The default flogo.json created by the create command from cli is not getting imported.
Command: flogo create myapp

Additional Information: The generated flogo.json does not have name tag in the "actions" and thus not getting imported. If we add the name tag to the flogo.json in the "actions", it is getting imported successfully.This might be helpful for fixing the issue.

**Comment by jpark800** [comment]
Yogita, please provide the flogo cli version and flogo.json.

**Comment by ykalidin** [comment]
Flogo.json

`{
  "name": "myapp2",
  "type": "flogo:app",
  "version": "0.0.1",
  "description": "My flogo application description",
  "triggers": [
    {
      "id": "my_rest_trigger",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/rest",
      "settings": {
        "port": "9233"
      },
      "handlers": [
        {
          "actionId": "my_simple_flow",
          "settings": {
            "method": "GET",
            "path": "/test"
          }
        }
      ]
    }
  ],
  "actions": [
    {
      "id": "my_simple_flow",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow",
      "data": {
        "flow": {
          "attributes": [],
          "rootTask": {
            "id": 1,
            "type": 1,
            "tasks": [
              {
                "id": 2,
                "type": 1,
                "activityRef": "github.com/TIBCOSoftware/flogo-contrib/activity/log",
                "name": "log",
                "attributes": [
                  {
                    "name": "message",
                    "value": "Simple Log",
                    "type": "string"
                  }
                ]
              }
            ],
            "links": [
            ]
          }
        }
      }
    }
  ]
}`

**Comment by mellistibco** [comment]
@ykalidin are you still having issues?

**Comment by ykalidin** [comment]
@mellistibco Yes, the issue is still there. The flogo created does not have the "name" tag in the flow.
Thus we are not able to import the flogo.json in the Flogo UI.

**Comment by fm-tibco** [comment]
The sample flow generated by the CLI now has name.  Please give it a try and let us know if it resolves your issue.

**Comment by ykalidin** [comment]
@fm-tibco We are still facing the issue. The "name" tag is added in flow. But, "name" tag should be added in the "actions" part for successful import.

**Comment by fm-tibco** [comment]
@ykalidin I added it to action.  I'll have to talk to the UI guys, because the name that the engine makes accessible to activities is under "flow"

**Comment by mellistibco** [comment]
@fcastill can we add this to our list of things to do? :)

**Comment by fcastill** [comment]
This was fixed by TIBCOSoftware/flogo-web#445 and it will be part of the v0.4.2 release.

**Comment by fcastill** [comment]
The fix for this issue was included in v0.5.0 release.
