### ISSUE TITLE
aws_iot sample

### ISSUE THREAD

**Issue by anshulsharmas** [TIBCOSoftware/flogo#56]
Hi,
Did anyone try executing the aws iot sample recently?

As per readme,command to mount things folder is as below:
` docker run -it -p 3303:3303 -v ${thingsFolderPath}:/tmp/flogo-web/build/server/test-engine/bin/things flogo/flogo-web`

On my machine, "/Users/anshul/Downloads/flogo" dir contains things dir with root-CA.pem.crt & a "flogo" dir with device.pem.crt & device.pem.key.
I am running below cmd to start docker container:
`docker run -it -p 3303:3303 --name testflogo -v /Users/anshul/Downloads/flogo:/tmp/flogo-web/build/server/test-engine/bin/things flogo/flogo-docker eula-accept`

I am getting below error:

> Error evaluating activity 'Update'[github-com-tibco-software-flogo-contrib-activity-awsiot] - open things/flogo/device.pem.crt: no such file or directory

What am I missing? Is the mount directory inside the container i.e.

> /tmp/flogo-web/build/server/test-engine/bin/things

 still same or has changed recently?

**Comment by torresashjian** [comment]
Hi @anshulsharmas, Have you tried running

`docker run -it -p 3303:3303 --name testflogo -v 
/Users/anshul/Downloads/flogo/things:/tmp/flogo-web/build/server/test-engine/bin/things flogo/flogo-docker eula-accept`

Instead?

**Comment by mellistibco** [comment]
Hi @anshulsharmas are you still having issues?

**Comment by mellistibco** [comment]
closing issue, please reopen if still a problem

**Comment by thanhngvpt** [comment]
Same issue. I run by copy and paste this command from flogo.io `docker run -it -p 3303:3303 flogo/flogo-docker eula-accept` When try to run an example i got error as image. I also tried to run command as @torresashjian suggested but error still there 
<img width="1437" alt="screen shot 2018-12-27 at 8 50 40 am" src="https://user-images.githubusercontent.com/19367683/50462030-2c641d80-09b5-11e9-8969-16706f66335c.png">
What wrong with me?
Many thanks.

**Comment by mellistibco** [comment]
@thanhngvpt the AWS IoT activity requires certificates that you download from the AWS IoT console (portal). You'll then need to place them in your app dir + the path specified in the error message. This will be a bit trickier if you want to test within the webui, you'll need to mount a dir when starting the docker image and place the certs in that location...
