### ISSUE TITLE
Create Custom Activity

### ISSUE THREAD

**Issue by Ganitagya** [TIBCOSoftware/flogo#57]
Hi,

While creating a custom activity as described in [Building your first activity](https://tibcosoftware.github.io/flogo/docs/create-activity), I ran the below command
```flogogen activity HelloWorld```

The "activity_test.go" thus created has below import statement:
```"github.com/TIBCOSoftware/flogo-lib/flow/test" ```
which is not present in the master branch.

Because of this ```go test``` fails.

Can anyone please tell what changes has to be done in the activity_test.go file ?

**Comment by fm-tibco** [comment]
The flogo-cli as been fixed.  If you'd like to correct it manually, change that line to 	"github.com/TIBCOSoftware/flogo-contrib/action/flow/test"

**Comment by Ganitagya** [comment]
I tried changing the import path for the test package and ran "go test" on the files created inside my activity I got the below error:

![image](https://user-images.githubusercontent.com/7741782/28966175-60c61912-7932-11e7-9fef-5f6d4194266f.png)


I have modified the files as per given in the docs.https://tibcosoftware.github.io/flogo/docs/create-activity.

The error is thrown by "TestEval" function of activity_test.go. 
I think it has to do something with the return type of Eval function of activity.go. Please correct me if I am wrong.

**Comment by fm-tibco** [comment]
Did you update your cli?  go get -u github.com/TIBCOSoftware/flogo-cli/...

**Comment by fm-tibco** [comment]
I've updated the documentation:

https://tibcosoftware.github.io/flogo/docs/create-activity

	You should have Flogo installed: go get github.com/TIBCOSoftware/flogo-cli

changed to:

	You should have Flogo CLI installed: go get -u github.com/TIBCOSoftware/flogo-cli/...

Code change:

 	func (a *MyActivity) Eval(context activity.Context) (done bool, evalError *activity.Error) {

 changed to:

	func (a *MyActivity) Eval(context activity.Context) (done bool, err error)  {

**Comment by Ganitagya** [comment]
Yes I updated flogo-cli.

The below error 
```activity_test.go:43: panic during execution: interface conversion: interface {} is nil, not string```
comes after changing 
```func (a *MyActivity) Eval(context activity.Context) (done bool, evalError *activity.Error) {```
to
```func (a *MyActivity) Eval(context activity.Context) (done bool, err error)  {```

**Comment by Ganitagya** [comment]
I will tell you the process I followed : 

1. Updated flogo-cli
2. Ran ```flogogen activity activityName``` 
3. Changed the import path of **test** package in **activity_test.go**
4.  ```go test```returns **PASS**
5. Made the changes to the JSON file and **activity.go** as mentioned in [Building your first activity](https://tibcosoftware.github.io/flogo/docs/create-activity) 
6. Changed the return type of **Eval** function in **activity.go** to **error**
7. ```go test``` fails and shows below error:

```
--- FAIL: TestEval (0.00s)
        activity_test.go:43: panic during execution: interface conversion: interface {} is nil, not string
FAIL
exit status 1
```

**Comment by mellistibco** [comment]
@Ganitagya are you still having issues?

**Comment by Ganitagya** [comment]
No, it worked after some changes in the activity.go and activity_test.go
