### ISSUE TITLE
is the flogo-web supposed to be open source at some point ?

### ISSUE THREAD

**Issue by ymolists** [TIBCOSoftware/flogo#60]
Thank you for your great and amazing work! 

There seems to be a missing piece in the puzzle in regards to the webui. Is this something on the radar ? Because building on flogo without the infrastructure to create the flow graph from a ui becomes very cumbersome.

**Comment by retgits** [comment]
Hi! You can get the WebUI from [Docker Hub](https://hub.docker.com/r/flogo/flogo-docker/)
```
docker pull flogo/flogo-docker
```

That will give you a docker container with the Web UI to create your flows.

Hope that solves your issue :)

**Comment by ymolists** [comment]
I did get the webui and its an amazing peice of code. I was just wondering if i should my hold breath for it being open sourced as well :)) And yes i can definitely respect the decision if you are not planning to make the flogo-web ui as open source with the same ASl2 license.

**Comment by mellistibco** [comment]
@ymolists Glad you like it! We've not yet decided if we'll make WebUI OSS. I don't want to rule anything out, you never know :)
