### ISSUE TITLE
Using Flogo on devices as bare-metal programs

### ISSUE THREAD

**Issue by ClumsyApe** [TIBCOSoftware/flogo#66]
Hello Flogo developers,

I recently started looking at Flogo. While I enjoy its simplicity of use, there's still something I don't get.
The project targets small devices with limited memory resources, but I can only generate ELF executables. Hence we need an ELF loader on the device to make it run, correct? Or does Flogo still need an underlying OS beneath it?

Thanks for your help!

**Comment by mellistibco** [comment]
Hi @ClumsyApe There are really two application variants that you can build with Flogo. The first being the Golang generated binary of Flogo, in which case, yes you do need an Operating System to run this. You can compile to a number of different platforms, Arm Linux for example.

Now, in Flogo WebUI you can select Device type apps. You currently need to use the flogo CLI to build these applications. Behind the scenes PlatformIO is used to build a native binary that can be used to flash microcontrollers (for example, an M0 on an Arduino).

Hope that helps.

**Comment by ClumsyApe** [comment]
Hi @mellistibco, thank you for your quick response. I understand much better now! I'll play a bit the CLI and see what I can do with it.

Cheers

**Comment by zejiangfish** [comment]
Hi @mellistibco , is there example or document for how to build application for arduino? Thanks a lot.
