### ISSUE TITLE
web ui not opening

### ISSUE THREAD

**Issue by neethuabu** [TIBCOSoftware/flogo#67]
Hi 
I obtained the flogo docker image
The terminal/console window indicating that the image is up and the webui is running. It asked me to open http://localhost:3303. 

But I get a site cannot be reached error

Any idea what could be wrong?

Thanks

**Comment by rkozhikk** [comment]
Can you run "docker ps" and verify the container is running and see the port number?

**Comment by neethuabu** [comment]
Hi,

yes, I have run docker ps -a and I do see it running on port 3303 as:


CONTAINER ID        IMAGE                       COMMAND                  CREATED
             STATUS                         PORTS                    NAMES
2c1638b5f40        flogo/flogo-docker:latest   "/tmp/flogo-web/do..."   About a
minute ago   Up About a minute              0.0.0.0:3303->3303/tcp   clever_hoo
er

**Comment by mellistibco** [comment]
Do you have anything that could block the network ports from binding? If you run a netstat do you see port 3303 bound? Do you see anything in the docker console logs for the image that you just started? Typically docker run -it -p 3303:3303 flogo/flogo-docker eula-accept is all you should need...

**Comment by neethuabu** [comment]
I dont think I have anything that could block the port binding.
I didnt seem to have any issues starting other types of processes and they did the port binding just fine. Although they were all 8 series port numbers.

What if I want to try to run this on an 8 series port, i tried to change the port number on docker run, but i always get the response that flogo started on 3303, is there not an option to change the port?

**Comment by neethuabu** [comment]
Also, yes netstat doest show any process listening on 3303. so there is definitely a problem

**Comment by mellistibco** [comment]
You can keep the container port at 3303 and just bind it to a different local port on your machine:

docker run -it -p 8099:3303 flogo/flogo-docker eula-accept

**Comment by neethuabu** [comment]
I had already tried it., but at the end of docker run it always says open localhost:3303. Anyway i disregarded it, but I tried on the new port, still same issue

2017-09-28T16:25:33.680Z - verbose: updateDB done.
2017-09-28T16:25:33.680Z - verbose: registerActivities success
2017-09-28T16:25:33.680Z - verbose: registerTriggers success
[log] start web server done.
flogo-web::server::ready

  ======================================================
                 ___       __   __   __ TM
                |__  |    /  \ / _` /  \
                |    |___ \__/ \__| \__/

   [success] open http://localhost:3303 in your browser
  ======================================================

**Comment by mellistibco** [comment]
Yes, that will say 3303 because that is the port being bound to in the container, but whatever port you specified on the docker run will be the local machine port. A netstat still shows nothing bound to the specified port?

**Comment by neethuabu** [comment]
yes, that is right. doesnt show port binding on new port

**Comment by mellistibco** [comment]
What OS and version of Docker are you using?

**Comment by fcastill** [comment]
Are you able to open other docker based web apps?
For example if you run the following and navigate to localhost:8098, does the page load?
`docker run -p 8098:80 dockercloud/hello-world`

**Comment by neethuabu** [comment]
Thanks everyone. I have the webui working now

It was not a flogo issue at all. It was a windows issue!. I had to set up port forwarding rules on virtualbox VM



For anyone with similar issue here is what you need to do:

Get Oracle VM Virtual box manager.

Got to Settings>Network>Adapter 1 > Advanced Port Forwarding

Add new rule. Set host and guest port as 3303 ( or any other port you want to listen to) leave hostip and guestip blank

**Comment by mellistibco** [comment]
Awesome and thanks for the tip @neethuabu

**Comment by tibcoflogolearner** [comment]
I had similar issue.....Thanks for the tip @neethuabu !

**Comment by neethuabacker** [comment]
thanks @tibcoflogolearner !
also fyi this is only needed for Docker toolbox for windows ( for older windows versions )
If you have newer windows you can go with Docker for windows, which doesn't need this setting. 
Also, setting up proxy on docker toolbox for windows is a pain ( if you need to do it )
I strongly recommend using docker for windows if you can

**Comment by ayh20** [comment]
FWIW - Port forwarding is one way to do it ... the other way is to find the IP address of the Docker VM .... then use that address as the HTTP address rather than localhost.
