### ISSUE TITLE
Issue pulling Flogo container from Docker

### ISSUE THREAD

**Issue by rickdantz** [TIBCOSoftware/flogo#69]
Hi I just installed the Docker Toolbox for Windows 7 successfully. But when I try to run following command I get an error. Any ideas what I could be doing wrong? 

       docker run -it -p 3303:3303 flogo/flogo-docker:latest eula-accept

I'm getting this error: 
$ docker run -it -p 3303:3303 flogo/flogo-docker eula-accept
Unable to find image 'flogo/flogo-docker:latest' locally
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Get http
s://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:
53: no such host.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

**Comment by fcastill** [comment]
The command is correct. This looks like a network problem, docker is unable to connect to its registry.

You might want to check your DNS, firewall or proxy/vpn configuration.

**Comment by mellistibco** [comment]
Hi @rickdantz are you still having issues?

**Comment by rickdantz** [comment]
Hi I was able to resolve this issue. Now I have other issues but I'll address them in another issue. Thanks for checking.
