### ISSUE TITLE
Go newbie - installed flogo ... flogogen not found

### ISSUE THREAD

**Issue by hansamann** [TIBCOSoftware/flogo#70]
I've followed the docs here https://tibcosoftware.github.io/flogo/extensions-developer/create-activity/ e.g.

go get -u github.com/TIBCOSoftware/flogo-cli/...
go get -u github.com/golang/lint/golint

but flogo / flogogen is not found - do I miss a step?

**Comment by fcastill** [comment]
You might be missing `$GOPATH/bin` in your path, that's why the executables are not found.

Some info about it:
https://golang.org/doc/code.html#GOPATH
https://github.com/golang/go/wiki/Setting-GOPATH

**Comment by hansamann** [comment]
Thx, that was of course the issue. I had no plan that go compiles them into this bin directory, as I said I am a total go newbie. Maybe that's worth adding for all the other newbies out there :-) Nice work and project otherwise!

**Comment by retgits** [comment]
@hansamann good feedback! We'll be sure to add it. Are there other topics that you'd like to see in such a "getting started" guide?

**Comment by hansamann** [comment]
I am sure many come from an existing Node-RED knowledge and it would make sense to have a comparison how both relate and what's better/different with flogo. I also think the command line creation of flows needs better documentation and explanations. Still exploring, will share my feedback as I discover more.
