### ISSUE TITLE
flogo create -f flogo.json failed with FATAL

### ISSUE THREAD

**Issue by lwlwlwlw** [TIBCOSoftware/flogo#71]
Can not create application from existing application definition file:

D:\tmp\flogo\ht>flogo create -f flogo.json
FATAL: command "create" failed: Cannot create project, directory 'D:\tmp\flogo\ht' already exists

========== flogo.json =============
{
  "name": "myApp",
  "type": "flogo:app",
  "version": "0.0.1",
  "description": "My flogo application description",
  "triggers": [
    {
      "id": "my_rest_trigger",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/rest",
      "settings": {
        "port": "9233"
      },
      "handlers": [
        {
          "actionId": "my_simple_flow",
          "settings": {
            "method": "GET",
            "path": "/test"
          }
        }
      ]
    }
  ],
  "actions": [
    {
      "id": "my_simple_flow",
      "name": "my simple flow",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow",
      "data": {
        "flow": {
          "name": "my simple flow",
          "attributes": [],
          "rootTask": {
            "id": 1,
            "type": 1,
            "tasks": [
              {
                "id": 2,
                "type": 1,
                "activityRef": "github.com/TIBCOSoftware/flogo-contrib/activity/log",
                "name": "log",
                "attributes": [
                  {
                    "name": "message",
                    "value": "Simple Log",
                    "type": "string"
                  }
                ]
              }
            ],
            "links": [
            ]
          }
        }
      }
    }
  ]
}

**Comment by mellistibco** [comment]
Try specifying the app name:

flogo create -f flogo.json AppName

**Comment by fm-tibco** [comment]
We are looking into this bug, if you don't specify a name it should default to the app name in the flogo.json

**Comment by lwlwlwlw** [comment]
Thank you for your help.

Great to know.

PS, flogo create -f flogo.json AppName worked.

**Comment by mellistibco** [comment]
This is resolved in the latest release.
