### ISSUE TITLE
Flow app directory

### ISSUE THREAD

**Issue by hansamann** [TIBCOSoftware/flogo#72]
Refering to the end of https://tibcosoftware.github.io/flogo/extensions-developer/create-activity/

I was a bit lost and started the docker container with my flogo ui and to my surprise, I discovered my HelloWorld app there. So was flogogen automatically installing the activity somehow? I would have prefered to do this manually but had no idea where my "flow directory" is - where is it? I assume in the docker container or is it linked to an outside volume?

**Comment by mellistibco** [comment]
Hi @hansamann flogogen does not install your activity, you would need to execute flogo install, and to that point, it would only install to your local app. The flow directory is the application directory.

flogo create myApp

./myApp would be the flow directory (the root of your app).

The Flogo WebUI contains a default HelloWorld flow within the Default app.

**Comment by hansamann** [comment]
Ok, seems there is some logical break in the howto. Am I correct to assume that the "flows" are comparable to node-red flows and they need to be executed in some kind of flow engine? In this case the flogo engine, which needs to be running somewhere. So do I have to ssh into the docker container where the UI (and I assume the engine) runs, too?

**Comment by mellistibco** [comment]
You build the Flows into binaries and you can run on the target platform that you built for. You do not need Flogo on the machine that you intend to run your application. You can build from the WebUI and download the binary for your platform.

**Comment by hansamann** [comment]
Thx @mellistibco for the explanatiosn. I was able to build the light switch example and it's happily running on a pi3 now. Great stuff.
