### ISSUE TITLE
Unknown command add

### ISSUE THREAD

**Issue by hansamann** [TIBCOSoftware/flogo#73]
Hi again, now onto creating an app, via this example: 

https://tibcosoftware.github.io/flogo/iot/how-to/

So I just created the app via flogo create myIotApp "somewhere" - in this case in my $home but that part worked as expected. But the first command to add the activities that are described in the reqcounter.json file already fails:

d061237:~/myIotApp>$ flogo add activity github.com/TIBCOSoftware/flogo-contrib/activity/log
FATAL: unknown command "add"

Any idea?

**Comment by mellistibco** [comment]
Documentation bug, it should be:

flogo install github.com/TIBCOSoftware/flogo-contrib/activity/log
