### ISSUE TITLE
timer trigger failed with "panic: interface conversion: interface {} is nil, not string"

### ISSUE THREAD

**Issue by lwlwlwlw** [TIBCOSoftware/flogo#76]
I exported project from flogo docker UI with timer (repeating=false) and log message(msg=hello world~~~~) as below(flogo.json) and execution failed with "panic: interface conversion: interface {} is nil, not string" in both Windows and Centos 7.

===== flogo.json ====
{
  "name": "runonce",
  "type": "flogo:app",
  "version": "0.0.1",
  "description": "",
  "triggers": [
    {
      "name": "Timer",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/timer",
      "description": "Simple Timer trigger",
      "settings": {},
      "id": "timer",
      "handlers": [
        {
          "settings": {
            "repeating": "false",
            "notImmediate": null,
            "startDate": null,
            "hours": null,
            "minutes": null,
            "seconds": null
          },
          "actionId": "flow_1"
        }
      ]
    }
  ],
  "actions": [
    {
      "name": "flow1",
      "data": {
        "flow": {
          "type": 1,
          "attributes": [],
          "rootTask": {
            "id": 1,
            "type": 1,
            "tasks": [
              {
                "id": 2,
                "name": "Log Message",
                "description": "Simple Log Activity",
                "type": 1,
                "activityType": "tibco-log",
                "activityRef": "github.com/TIBCOSoftware/flogo-contrib/activity/log",
                "attributes": [
                  {
                    "name": "message",
                    "value": "hello world ~~~~",
                    "required": false,
                    "type": "string"
                  },
                  {
                    "name": "flowInfo",
                    "value": "false",
                    "required": false,
                    "type": "boolean"
                  },
                  {
                    "name": "addToFlow",
                    "value": "false",
                    "required": false,
                    "type": "boolean"
                  }
                ]
              }
            ],
            "links": [],
            "attributes": []
          }
        }
      },
      "id": "flow_1",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow"
    }
  ]
}

==== error msg ===
D:\dev\go\src\github.com\lwlwlwlw\flogo-project\runonce\bin>runonce.exe
2017-10-23 19:37:24.178 DEBUG  [engine] - Registering action factory: 'github.com/TIBCOSoftware/flogo-contrib/action/flow'
2017-10-23 19:37:24.190 DEBUG  [engine] - Registering activity: 'github.com/TIBCOSoftware/flogo-contrib/activity/log'
2017-10-23 19:37:24.191 DEBUG  [engine] - Registering trigger factory: 'github.com/TIBCOSoftware/flogo-contrib/trigger/timer'
2017-10-23 19:37:24.192 INFO   [engine] - Engine: Starting...
2017/10/23 19:37:24 In init, id: 'timer', Metadata: '&{ID:github.com/TIBCOSoftware/flogo-contrib/trigger/timer Handler:0xc0420c0d20 Settings:map[] Output:map[params:0xc04206f950 content:0xc04206f9b0] Reply:map[]}', Config: '&{Name:Timer Id:timer Ref:github.com/TIBCOSoftware/flogo-contrib/trigger/timer Settings:map[] Output:map[] Handlers:[0xc042102090] Outputs:map[]}'
2017-10-23 19:37:24.193 DEBUG  [engine] - Uncompressed flow with id 'flow_1' added
2017-10-23 19:37:24.194 DEBUG  [engine] - ActionRunner Service: Starting...
2017-10-23 19:37:24.194 DEBUG  [engine] - Starting worker with id '1'
2017-10-23 19:37:24.194 DEBUG  [engine] - Starting worker with id '2'
2017-10-23 19:37:24.194 DEBUG  [engine] - Starting worker with id '3'
2017-10-23 19:37:24.195 DEBUG  [engine] - Starting worker with id '4'
2017-10-23 19:37:24.195 DEBUG  [engine] - Starting worker with id '5'
2017-10-23 19:37:24.195 DEBUG  [engine] - ActionRunner Service: Started
2017-10-23 19:37:24.196 INFO   [engine] - Engine: Starting Services...
2017-10-23 19:37:24.196 INFO   [engine] - Engine: Started Services
2017-10-23 19:37:24.196 DEBUG  [engine] - Trigger [ 'timer' ]: Starting...
2017/10/23 19:37:24 Start
2017/10/23 19:37:24 Processing handlers
2017/10/23 19:37:24 Repeating:  false
2017/10/23 19:37:24 Scheduling a run one time job
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/TIBCOSoftware/flogo-lib/core/trigger.(*HandlerConfig).GetSetting(...)
        D:/dev/go/src/github.com/lwlwlwlw/flogo-project/runonce/vendor/src/github.com/TIBCOSoftware/flogo-lib/core/trigger/config.go:115
github.com/TIBCOSoftware/flogo-contrib/trigger/timer.getInitialStartInSeconds(0xc042102090, 0xc0420314a0)
        D:/dev/go/src/github.com/lwlwlwlw/flogo-project/runonce/vendor/src/github.com/TIBCOSoftware/flogo-contrib/trigger/timer/timer.go:176 +0x122d
github.com/TIBCOSoftware/flogo-contrib/trigger/timer.(*TimerTrigger).scheduleOnce(0xc0421103c0, 0xc042102090)
        D:/dev/go/src/github.com/lwlwlwlw/flogo-project/runonce/vendor/src/github.com/TIBCOSoftware/flogo-contrib/trigger/timer/timer.go:97 +0xac
github.com/TIBCOSoftware/flogo-contrib/trigger/timer.(*TimerTrigger).Start(0xc0421103c0, 0xf, 0xc0420313b0)
        D:/dev/go/src/github.com/lwlwlwlw/flogo-project/runonce/vendor/src/github.com/TIBCOSoftware/flogo-contrib/trigger/timer/timer.go:65 +0x5a6
github.com/TIBCOSoftware/flogo-lib/util.StartManaged(0xc0420deec0, 0x13, 0x36a8680, 0xc0421103c0, 0xc0421103c0, 0xc0420deec0)
        D:/dev/go/src/github.com/lwlwlwlw/flogo-project/runonce/vendor/src/github.com/TIBCOSoftware/flogo-lib/util/managed.go:62 +0xf6
github.com/TIBCOSoftware/flogo-lib/engine.(*EngineConfig).Start(0xc04206c550, 0xa1c380, 0xc04206c550)
        D:/dev/go/src/github.com/lwlwlwlw/flogo-project/runonce/vendor/src/github.com/TIBCOSoftware/flogo-lib/engine/engine.go:143 +0x419
main.main()
        D:/dev/go/src/github.com/lwlwlwlw/flogo-project/runonce/src/runonce/main.go:37 +0xac

**Comment by Adirio** [comment]
You should probably open an issue [here](https://github.com/TIBCOSoftware/flogo-contrib) as there is where the Timer trigger is hosted.

**Comment by fm-tibco** [comment]
I have created an issue in flogo-contrib:#137.  It should now handle a nil startDate (which will be interpreted as start immediately).  I have created a pull request for this as well.

**Comment by lwlwlwlw** [comment]
Thank you for your help!
Glad to know this is fixed. And I will open issue in the right place.

**Comment by mellistibco** [comment]
fixed in TIBCOSoftware/flogo-contrib#137
