### ISSUE TITLE
Is it possible to update souce code under vendor folder with command like go get -u

### ISSUE THREAD

**Issue by lwlwlwlw** [TIBCOSoftware/flogo#77]
I am learning to develop trigger/activity, and create flogo project to test it.
After updated trigger/activity code I have to delete flogo project and re-generate it from flogo.json file again to download the updated trigger/activity code. So I am wondering if it is possible to update local trigger/activity code required by flogo project using command like "flogo update" or something else.

Thanks.

**Comment by mellistibco** [comment]
We currently don't have a flogo update type of command, however, gb vendor update should do the trick. More info: https://godoc.org/github.com/constabulary/gb/cmd/gb-vendor

**Comment by lwlwlwlw** [comment]
Great! Thank you.
