### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by magallardo** [TIBCOSoftware/flogo#78]
The documentation for "How-to for IOT" seems to be out of date. 

Executing the following commands as indicated in the instructions throws the following errors:

flogo install activity github.com/TIBCOSoftware/flogo-contrib/activity/log
Error: Too many arguments given
Usage:
    flogo  install [-v version][-p] contribution

flogo add flow reqcounter.json
FATAL: unknown command "add"

Usage:
    flogo <command> [arguments]

**Comment by mellistibco** [comment]
Documentation has been updated via PR #79
