### ISSUE TITLE
Metadata Type in flogo.json is not being Resolved properly.

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/flogo#87]
If we give an array to string parameter the value is being mapped and the message is being logged in the output.
`"metadata": {
        "input": [
          {
            "name": "id",
            "type": "array"
          }
        ]
      }`
In the above example, "id" is string but when we map it to type array, no error is seen while creating the app and the "id" is still getting logged as string.

Below is the complete json:
`{
  "name": "test-flogo",
  "type": "flogo:app",
  "version": "0.0.1",
  "description": "",
  "triggers": [
    {
      "name": "Receive HTTP Message",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/rest",
      "description": "Simple REST Trigger",
      "settings": {
        "port": "9096"
      },
      "id": "receive_http_message",
      "handlers": [
        {
          "settings": {
            "method": "GET",
            "path": "/pets/:name",
            "autoIdReply": null,
            "useReplyHandler": null
          },
          "actionMappings": {
            "input": [
              {
                "type": 1,
                "mapTo": "name",
                "value": "pathParams.name"
              }
            ],
            "output": []
          },
          "actionId": "hello"
        }
      ]
    }
  ],
  "actions": [
    {
      "data": {
        "flow": {
          "name": "Hello",
          "type": 1,
          "attributes": [],
          "rootTask": {
            "id": 1,
            "type": 1,
            "tasks": [
              {
                "id": "log_2",
                "name": "Log Message",
                "description": "Simple Log Activity",
                "type": 1,
                "activityType": "tibco-log",
                "activityRef": "github.com/TIBCOSoftware/flogo-contrib/activity/log",
                "attributes": [
                  {
                    "name": "message",
                    "required": false,
                    "type": "string"
                  },
                  {
                    "name": "flowInfo",
                    "value": "true",
                    "required": false,
                    "type": "boolean"
                  },
                  {
                    "name": "addToFlow",
                    "value": "true",
                    "required": false,
                    "type": "boolean"
                  }
                ],
                "inputMappings": [
                  {
                    "type": 1,
                    "value": "${name}",
                    "mapTo": "message"
                  }
                ]
              }
            ],
            "links": [],
            "attributes": []
          }
        }
      },
      "id": "hello",
      "metadata": {
        "input": [
          {
            "name": "name",
            "type": "array"
          }
        ]
      },
      "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow"
    }
  ]
}`

**Comment by mellistibco** [comment]
The input to the log type is cast as a string, so it will still output arrays, objects, etc

**Comment by mellistibco** [comment]
@ykalidin do you have any additional info you can add or is everything as expected?

**Comment by ykalidin** [comment]
@mellistibco  I have checked the same for Rest Service. Its working fine.Thanks for correcting my understanding on this.
