### ISSUE TITLE
REST App created by flogo UI has different behaviour to SAME app created by flogo commandline.

### ISSUE THREAD

**Issue by prithvimoses** [TIBCOSoftware/flogo#92]
I created a simple flogo REST app (see attached app) that has a log activity and a rest reply. It works when the app is built from the flogo CLI as expected but does not work (incorrect reply) when it is built from the flogo webUI.

I'm using the current version 0.4.1

[app.txt](https://github.com/TIBCOSoftware/flogo/files/1490031/app.txt)

**Comment by mellistibco** [comment]
What is the reply from webui?

**Comment by prithvimoses** [comment]
Reply from the webui build version returns the "id" and reply from the cmd line created version returns the correct reply message configured in the reply activity.

**Comment by mellistibco** [comment]
This was an issue with webui not setting the explicitReply property on the flow. This will be fixed with the latest build of webui slated to be available very soon.

**Comment by mellistibco** [comment]
This should be resolved, if not, please reopen.
