### ISSUE TITLE
Web site home page, www.flogo.io

### ISSUE THREAD

**Issue by troyf** [TIBCOSoftware/flogo#97]
The home page, www.flogo.io does not answer the question or have a link to answer the question: "what exactly is flogo". Those wishing to know the answer to that question are forced to endure some frustracion and then to use third party sites to describe your 'product', for example: https://dzone.com/articles/project-flogo-golang-powered-open-source-iot-integ
Troy.
#

**Comment by mellistibco** [comment]
Thanks for the feedback @troyf. We're getting ready to revamp flogo.io.

**Comment by mellistibco** [comment]
The flogo.io site, while still in need a major overhaul, is much more informative than it was in the past. Closing for now and will open a new issue to capture the need for an entire site overhaul.
